### ISSUE TITLE
Proposal: Photoshop/Sketch/etc. plugin

### ISSUE THREAD

**Issue by vvasilev-** [presentator/presentator#1]
It will be great if the users can upload their screens directly from the software that they use. 😃

**Comment by vvasilev-** [comment]
@ganigeorgiev I have some experience with Photoshop extensions, so probably I can help with this one. What do you think? 😃

**Comment by ganigeorgiev** [comment]
@vvasilev- That would be great :).

There is a [REST API](https://api.presentator.io/doc/index.html) available but it is still in very early development (these days I will add request rate limiter and couple of more new services to the Screen and Project models).

**Comment by Xaviju** [comment]
I can work on the Inkscape plugin. I'll check the API, thanks :)
btw, great project!

**Comment by alapiere** [comment]
I would love a sketch plugin .. Cannot convince my designer to switch to presentator otherwise , but unfortunately I don't have the required dev skills :(

**Comment by der-On** [comment]
The Sketch file format is basically a ZIP containing assets and lots of very huge json files. The main problem is, that the file format changes fairly often and is undocumented. Reverse engeneering it could take some time. In theory one could write a standalone sketch to presentator importer even without having a mac.

**Comment by lazmo88** [comment]
Would love Photoshop extension! :)

**Comment by alapiere** [comment]
just gave a quick look at evrybo sketch plugin export code,  
(https://app.evrybo.com/public/download/evrybo_sketchplugin.zip) 
doesn't seems much complicated, most of the code is menu UI handling;
Although it's proprietary code, not sure how much one can 'inspire' from this.

**Comment by flayks** [comment]
+1 for Sketch, that would be great!

**Comment by ganigeorgiev** [comment]
I see that many of the users are requesting a Sketch plugin, but unfortunately at the moment I'm not planning to start working on it and will try to focus on other features (mainly improving notifications and comments).

[Adobe XD](https://github.com/presentator/presentator-xd) and [Figma](https://github.com/presentator/presentator-figma) plugins are available, so if anyone wants to pick this issue, they can be used as reference (2 views are required - login and export).

**Comment by almrac** [comment]
+1 for Sketch, that would be great!

**Comment by vocso** [comment]
I agree, sketch will be a great addition to this already wonderful project. But sadly, I don't have that kind of expertise :(

**Comment by lid3rs** [comment]
Sketch plugin, yes!

**Comment by fabianmossberg** [comment]
I'm gonna join in the line of people who would love a Sketch plugin!

**Comment by ganigeorgiev** [comment]
Presentator v3 will be released soon (see https://github.com/presentator/presentator/issues/183#issuecomment-1899227611) and it comes with a new web API based on [PocketBase](https://github.com/pocketbase/pocketbase).

I'll close the issue for now as I don't have time nor access to a mac to work on a Sketch plugin, but if anyone wants to work on this you can refer to the [recently updated Figma plugin](https://github.com/presentator/figma) which supports both Presentator v2 and v3 APIs.
