### ISSUE TITLE
Date of comment in future

### ISSUE THREAD

**Issue by MDXDave** [presentator/presentator#108]
![image](https://user-images.githubusercontent.com/6099976/62497648-db36ca80-b7dc-11e9-8f94-84b06533bb58.png)

I have added a comment to a screen a few minutes ago, it will be shown "in 2 hours" instead of "now" or "for 2 minutes".

**Comment by ganigeorgiev** [comment]
@MDXDave I'm unable to reproduce it (you should see something like "a few minutes ago", "2 minutes ago", etc.).

Does this happen locally or on the free service (https://app.presentator.io)? 
What is your local (browser) timezone?

**Comment by MDXDave** [comment]
Hm... on the free service it works as expected.

My browser timezone is "Europe/Berlin"

The server timezone is "Europe/Berlin" too:

>  Local time: Tue 2019-08-06 14:23:40 CEST
  Universal time: Tue 2019-08-06 12:23:40 UTC
        RTC time: Tue 2019-08-06 12:23:40
       Time zone: Europe/Berlin (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

**Comment by ganigeorgiev** [comment]
That is very strange. If you are running on VM/containers, could you verify that your instance is in sync with the host (in the past I've experienced time syncing issues with docker on AWS)?.

**Comment by ganigeorgiev** [comment]
@MDXDave I'm unable to reproduce it locally. My guess is that the server clock is out of sync. If you think that this is a Presentator bug, please comment and I'll reopen the issue.
