### ISSUE TITLE
Feedback: functioning/purpose of template

### ISSUE THREAD

**Issue by keunes** [presentator/presentator#109]
I've just started to use Presentator.io and everything is very intuitive, except I didn't really understand the idea of (hotspot) templates immediately.

When playing with it I noticed the following:
A template is something you can take, and use as a starting point to build something new (think of word documents). That's not the case here; when making changes to a hotspot in screen 2 that originally was added to the template in screen 1, applies the changes also to screen 1. This shows that the 'templates' aren't used as a template but rather are still a linked building block. To me they feel more like 'Hotspot groups' and I think that renaming them as such would convey the working of it a bit clearer.

To further increase understanding maybe adding a little circle with a question mark right next to the templates menu could open a small modal window with a brief explanation.

Otherwise: awesome tool :+1:

**Comment by ganigeorgiev** [comment]
@keunes Thank you for the feedback. The naming was borrowed from InVision and I thought that using similar terms will make the transition to Presentator easier.

For now I'll leave the name as it is, but I'll consider adding a tooltip next to the "Include in template" hotspot control in the next release (if you have a suggestion for the help text, please add it as comment).

**Comment by ganigeorgiev** [comment]
Merged in master and included in v2.1.0 release.
