### ISSUE TITLE
Make whole item area clickable

### ISSUE THREAD

**Issue by keunes** [presentator/presentator#110]
Projects and Screens are essentially a big button to go one level deeper in the structure. Currently the preview area is highlighted when hovering the item, and the eye icon isn't boxed which makes it seem like the whole highlighted area is clickable. Yet in fact only the eye icon is clickable.
![Screenshot from 2019-08-11 12-18-06](https://user-images.githubusercontent.com/11229646/62832724-6a0b7300-bc33-11e9-9c9c-b8178d13c4f7.png)

It would be nice if the whole highlighted area would be clickable, to 'open' the item - of course except the areas already clickable for multi-select and the drop-down menu.

**Comment by ganigeorgiev** [comment]
Merged in master and included in v2.1.0 release.

**Comment by keunes** [comment]
Cool, thanks!
