### ISSUE TITLE
Remove need to click 'Save template' when creating new template from hotspot

### ISSUE THREAD

**Issue by keunes** [presentator/presentator#111]
~On Presentator.io, when creating/editing a hotspot, ticking the 'Include in template' box and creating a new template (selecting '+ New template' and entering a template name), the new template isn't saved.~

Edit: I totally missed the 'Save template' button. It would be nice if the new template gets saved/created when clicking the hotspot Create/Update button, as to remove the need for the 'Save template' button. The 'form within a form' with its own save button isn't really an expected pattern. If a separate button is needed to actively save the new template, I think it would be clearer to instead have a new modal window with a name field & save button.

**Comment by ganigeorgiev** [comment]
The idea of a separate "Save template" button is to allow reorganizing and creating several templates within a single hotpost popover.
I think that adding a new modal just for a single meta field is a little excessive and therefore I'll just add a frontend validator for the template title when "+ New template" option is selected.

**Comment by ganigeorgiev** [comment]
Merged in master and included in v2.1.0 release.
