### ISSUE TITLE
New screen position option: centered (vis-a-vis browser window)

### ISSUE THREAD

**Issue by keunes** [presentator/presentator#112]
When creating/editing a hotspot and choosing to link it to 'Screen as overlay' it already is possible to select 'Center'. This will present the overlay screen in the centre of the underlying screen.

When adding a log-in screen (representing modal window) through a hotspot overlaying a long page, this means that the log-in screen might get displayed outside the current view in the browser window (i.e. that you'd have to scroll down to see the log-in screen).

It would be nice to add a new option which will display the overlay screen in the centre of the browser window, so that you have the following 'centered' options:
* Centered in screen
* Centered in browser window

Not sure if the proposition 'in' is correct here, or that 'from' would be better ('relative to' or 'vis-a-vis' are too long so not an option really).

**Comment by keunes** [comment]
Actually I'm thinking now that this relativity also may apply to 'top' and 'bottom', maybe even to 'left' and 'right'. So actually this could be a whole new setting:
Relative to `screen` / `browser window`:
![Screenshot_2019-08-11 Presentator-mockup](https://user-images.githubusercontent.com/11229646/62834742-f11b1400-bc50-11e9-8457-7f84bd0d1195.png)

**Comment by ganigeorgiev** [comment]
@keunes I think with a checkbox "Fix position of overlay" will be better (similar to InVision).

**Comment by keunes** [comment]
I'm not sure if it's very clear when the option says 'Fix position of overlay'. Some modal windows on different websites can be moved by the user, where enabling this setting could mean to prevent that. This string could also represent current behaviour (it's currently fixed and doesn't move when resizing the browser window); will current behaviour be maintained by enabling the setting by default?

To me such string doesn't indicate what the point of reference is for 'bottom' or 'centre'. So if such setting does represent it in InVision, then I think they're setting a wrong example ;)

**Comment by ganigeorgiev** [comment]
@keunes To me "_Fix the overlay position relative to the preview container_" is probably more accurate, but it is too long (in Bulgarian is even longer). For now I'll leave "Fix position of overlay", but if you have any other suggestion for the label, please comment and I'll consider replacing it.

**Comment by ganigeorgiev** [comment]
Merged in master and included in v2.1.0 release. Once again, if you have a suggestion for different label, please comment and I'll consider replacing it.

**Comment by keunes** [comment]
Sorry, I had my parents-in-law visiting in the meantime. I agree the string you mentioned is too long. But to shorten it, I would take the 2nd half of the string, which is much more descriptive than the first part: _Position relative to preview container_

Also, I see it's now separate from the other position settings; I'd move it up so that at least it directly follows off-set (which is related):
![afbeelding](https://user-images.githubusercontent.com/11229646/63266191-a53f1f00-c28f-11e9-9706-e7bfa4db9897.png)

(I think it'd make even more sense to have such setting right from/right below the 'Position' setting as they're strongly related with the one impacting the behaviour of the other, but I understand that's a less visually appealing.)

Thanks anyway for implementing this!

**Comment by ganigeorgiev** [comment]
In v2.1.1 I've moved the checkbox right after the offset field.

But I disagree with your suggestion for the label. I think having "fix" in the label makes more sense because it emulates the same behavior as `position: fixed` in css.

**Comment by keunes** [comment]
Sorry for the silence in the meantime. As a regular user without much experience in design & with related software, fix seems just weird to me. Anyway.
I wouldn't know how to translate that, though. Would you have access to such programmes, and be able to switch languages to see how they call it?

**Comment by ganigeorgiev** [comment]
@keunes Sorry, I don't think there are many multilingual design tools. Before Presentator, me and my cowerkers previously used mainly Symu and Invision and both shares similar terminology (Symu doesn't have such advanced controls for the hotspots, but they have "Fixed element" and "Fixed group" for static header/footer).

If the translation in your language doesn't sound natural, it's OK to change it accordingly. The current Bulgarian translation is "Фиксирай позицията на овърлейа" which is very close to the English source label.
