### ISSUE TITLE
Migration seems not complete

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#115]
## Summary

Because I'm working with the first version of Presentator, I'm trying the migration locally first.

## Current behavior

1. I followed the migration instructions: https://github.com/presentator/presentator/blob/master/UPGRADE.md
2. First strange behavior, none of the projects appears 😱. When I performed a search, I successfully found project... After a lot of refreshes, my project finally appears 🤪
3. Some projects don't work anymore. I have the following error:

<img width="1757" alt="Screen Shot 2019-08-15 at 19 30 47" src="https://user-images.githubusercontent.com/15279205/63133463-52b1ea00-bf93-11e9-8470-b04309902cb9.png">

If I perform a search, I can find my files but when I click on one of them, I have an error:

<img width="424" alt="Screen Shot 2019-08-15 at 19 21 27" src="https://user-images.githubusercontent.com/15279205/63133489-6d845e80-bf93-11e9-934f-0bc76332b6c6.png">

Here, the docker logs error in accordance with the event:

```
presentator    | 192.168.0.1 - - [15/Aug/2019:23:32:58 +0000] "GET /api/screens?page=1&per-page=200&envelope=true&search[prototypeId]=27&search[title]= HTTP/1.1" 500 671 "http://localhost:8082/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3872.0 Safari/537.36 Edg/78.0.244.0"
presentator    | 192.168.0.1 - - [15/Aug/2019:23:33:05 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.1.31 (internal dummy connection)"
```

**Comment by ganigeorgiev** [comment]
@Laul0 This is probably related to the memory limit in FileStorageBehavior (yesterday @der-on pointed that in [gitter](https://gitter.im/presentatorio/presentator)). If you have a lot of projects or projects with large screens, it may take some time to create all preview thumbs (first time only).

I removed the ini_set call in v2.0.6 release (will add later some recommendation for php.ini settings). Please update your installation and increase if necessary the memory_limit in your php.ini configuration.

If that doesn't work, please post your latest php error logs and/or enable the api debug mode, by changing `YII_DEBUG` to `true` and `YII_ENV` to `dev` in `/path/to/app/web/api/index.php`

**Comment by Laul0** [comment]
Thx for your answer:

1. I set up the `pnp.ini` like that

```ini
post_max_size       = 128M
upload_max_filesize = 128M
max_execution_time  = 60
memory_limit        = 256M
```

Noted, I'll update with the latest version and keep you in touch

**Comment by Laul0** [comment]
Debug mode enable, and here the result (like explained in gitter):
<img width="454" alt="Screen Shot 2019-08-16 at 10 58 46" src="https://user-images.githubusercontent.com/15279205/63176967-ebd51500-c014-11e9-9cb2-d291b0888329.png">

**Comment by ganigeorgiev** [comment]
@Laul0 Increasing the memory limit to 384M or 512M should fix the issue (you may need to restart/rebuild your docker containers)

*Note that this limit is probably required only for the initial thumbs generation (I'll make a research to improve the resource consumption in future releases). For newly created projects, the screen thumbs are generated one by one and 256M should be enough in most cases.*

**Comment by Laul0** [comment]
I increased the memory by two and it works!
I find all of my projects 🤗

Thank you.

> Note: maybe add this case into the instruction of migration and indicate that increase the memory temporary until all of projects have been opened once at least?

**Comment by Laul0** [comment]
Just a question? It is possible to create a sort of "warmup" to simulate an opening for each project? (potentially useful if someone have a lot of projects)

**Comment by ganigeorgiev** [comment]
I've added in the `develop` branch a helper console command - https://github.com/presentator/presentator/commit/6b2f6db26be0abd447617b594f23af8ee4f2f7a5 (haven't tested it with large number of screens yet). Example usage:
```bash
php yii screens/generate-thumbs

# or if you are running the docker dev setup
./compose/scripts/api php yii screens/generate-thumbs
```
