### ISSUE TITLE
Bug: save button not visible on small screen

### ISSUE THREAD

**Issue by keunes** [presentator/presentator#116]
My laptop has a relatively small screen, and when the hotspot modal window is open and I am creating a new template, the 'save' button isn't fully visible, and I can't scroll the page to view the 'Save' button:
![Screenshot_2019-08-19 Presentator](https://user-images.githubusercontent.com/11229646/63267280-f7813f80-c291-11e9-9592-de04b9ffafd9.png)

I think this follows #111.

**Comment by ganigeorgiev** [comment]
Fixed and included in v2.1.1 release.

*There is still a lot that need to be improved for smaller device screens, but that will be handled in  #114.*

**Comment by keunes** [comment]
Grand, thanks!
