### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by mokra** [presentator/presentator#117]
I've tried to install the starter version on a php 7.0 without docker and received some errors

```
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/vhosts/pitanik.de/oc.pitanik.de/present/starter/vendor/presentator/api/base/Starter.php on line 86

Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/vhosts/pitanik.de/oc.pitanik.de/present/starter/vendor/presentator/api/base/Starter.php on line 86
```

what might be the problem here?
I actually would like to install developer version, bud I dont have docker. Do you have an installation instruction for that?

**Comment by ganigeorgiev** [comment]
@mokra Presentator requires PHP 7.1+.

For development setup without docker, you have to install the api and spa packages manually by following their installation instructions:
- API - https://github.com/presentator/presentator-api#installation
- SPA - https://github.com/presentator/presentator/tree/master/packages/spa#installing

Note that you will probably have to change the SPA env config file to point to your API web address.

**Comment by mokra** [comment]
thanks!
