### ISSUE TITLE
Unable to set allowedRegistrationDomains

### ISSUE THREAD

**Issue by panchtatvam** [presentator/presentator#118]
Version 1 allowed setting up of `allowedRegistrationDomains` in params-local.php config file to allow registration from only certain domains. Using this setting in v2 doesn't yield any results.

Is there a new setting ? Possibly via console or API ?

**Comment by ganigeorgiev** [comment]
@panchtatvam Yes, v2 comes with more configuration options and the following parameters were introduced - `onlyDomainsRegisterFilter` and `exceptDomainsRegisterFilter`.

You could find more about the supported parameters by checking the main api `params.php` config file - https://github.com/presentator/presentator/blob/master/packages/api/config/params.php#L42
