### ISSUE TITLE
Super admin can't delete users

### ISSUE THREAD

**Issue by panchtatvam** [presentator/presentator#119]
Super admin account has no option to delete users from the UI. Only `Edit` option is visible but no delete option.
![Screenshot_2019-10-04 Presentator](https://user-images.githubusercontent.com/1580970/66202905-8b815c00-e6c4-11e9-99ee-bf949eb65c7e.png)

**Comment by panchtatvam** [comment]
Found the delete button at the top right at the user page. My bad.
![Screenshot_2019-10-04 Presentator(1)](https://user-images.githubusercontent.com/1580970/66203379-d780d080-e6c5-11e9-98c1-156073f5cfd8.png)

**Comment by ganigeorgiev** [comment]
@panchtatvam I'm glad you found it. The link is intentionally "hided" to prevent deletion by mistake. 

_Note: Projects that have only 1 owner/administrator will be also deleted if the same user is deleted._
