### ISSUE TITLE
Reverse proxy example configuration

### ISSUE THREAD

**Issue by rakshith-ravi** [presentator/presentator#120]
Hey,

I was trying to setup a presentator instance on my server. I followed the steps mentioned in the documentation (starter package, without docker). However, every time I try to create a user account, it gives me a 404 page. I have a feeling something is wrong with my reverse proxy configuration. Could you please help me with an example configuration for nginx that I can take a look at? If not an example configuration, could you please let me know what folders should be exposed and what shouldn't? That way, I'll be able to set it up based on that

OS: Ubuntu 18.04
Reverse proxy: Nginx

Thanks

**Comment by ganigeorgiev** [comment]
@rakshith-ravi Here is a very robust nginx configuration (rate limiting, csp and other security headers are not included):

```nginx
server {
    charset utf-8;
    client_max_body_size 128M;

    listen 80; ## listen for ipv4

    server_name example.com;
    root        /var/www/presentator-starter/web;
    index       index.html index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    # redirect everything that isn't a real file to index.php
    location /api {
        try_files $uri $uri/ /api/index.php$is_args$args;
    }

    # define error page
    error_page 404 = @notfound;

    # error page location redirect 302
    location @notfound {
        return 302 /#/not-found;
    }

    # resolve php files
    # !change to your actual php environment setup
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
    }

    location ~* /\. {
        deny all;
    }
}
```
In general - everything located in the `web` directory should be accessible. If that doesn't help, please attach your recent error logs.

**Comment by rakshith-ravi** [comment]
Yes. That configuration seems to have fixed it. Thanks a ton
