### ISSUE TITLE
pt-BR translation on 100% - but it needs review

### ISSUE THREAD

**Issue by cadu-leite** [presentator/presentator#122]
last weekend I've finished  the pt-BR translation. 

the translation needs be reviewed.
We may have pt-BR interface on next release.

**Comment by ganigeorgiev** [comment]
@cadu-leite You should have Reviewer role in Transifex. Feel free to update and review the translations when you find time. If you need additional context for some of the strings, [create an issue or comment in Transifex](https://docs.transifex.com/translation/tools-in-the-editor#comments) (note that commenting sends notification only if the user is mentioned).

_If you think that the current translations shouldn't be public, please let me know and I'll temporary "hide" them in v2.3.1 release._

**Comment by cadu-leite** [comment]
well, the translation looks ok for me.  The problem is ... I did it myself ... 

For sure I had doubts sometimes because the lack of context.  

But may be, its worth to publish and check it on interface - I trust my job ;) 
 ..  thought.
