### ISSUE TITLE
Replace a screen by drag & drop

### ISSUE THREAD

**Issue by flayks** [presentator/presentator#124]
I found pretty difficult to replace a screen by uploading another image. That would be easier, as InVision does, to replace a screen's image by drag & dropping it on the actual screen or thumbnail 👌(and not click on the screen's settings, replace image, for each screen)

**Comment by ganigeorgiev** [comment]
Implemented in v2.4.0 release.

Now you could replace a single screen by drag&drop an image on the screen thumb and preview or by clicking on the Replace screen link in the screen settings popover.

A confirmation message could popups if the new image has lower width/height from the original one (could results in comments/hotspots misplacement).
