### ISSUE TITLE
Rename a screen

### ISSUE THREAD

**Issue by flayks** [presentator/presentator#125]
Maybe I haven't seen the option yet but I feel that we can't change a screen's name? That would be  pretty handy especially with these files names ending by @2x or something.

**Comment by flayks** [comment]
My bad, it's on the screen's settings. Though, that would be easier to change the screen name from the prototype's list (in place), a bit like how you can quickly rename a Project name.

**Comment by ganigeorgiev** [comment]
Implemented in v2.4.0 release.

Now all listing box items (projects, screens, guideline assets) are unified and could be renamed by clicking directly on their title.
