### ISSUE TITLE
Change screens' background color globally

### ISSUE THREAD

**Issue by flayks** [presentator/presentator#126]
As opposed to change a screen's background one by one, that would be convenient, as InVision has this option, to change the background globally for every screens in the prototype.

**Comment by ganigeorgiev** [comment]
Implemented in v2.4.0 release.

To apply bulk operation you could click on the icon next to the alignment, background, fixed header and fixed footer options:
![bulk_apply_background_example](https://i.imgur.com/soGyQ3O.png)
