### ISSUE TITLE
Proposal: pinned project

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#128]
## Summary

Like the issue #75, from the projects pages, all projects are visible in order of their creation date.
Because some people generally use the same project(s), it can be useful to put them at the top of the list.

## Current behavior

All projects are visible in the projects page and are "sorted" by the creation date.
If you still using old project(s), this one can be "hidden" - you have to click on "see more" to retrieve them.

## Expected behavior

A feature that allow to push some projects at the top the the active projects and all projects views.

Here, a mockup:
![Screen Shot 2020-02-18 at 15 45 39](https://user-images.githubusercontent.com/15279205/74776892-6f8ee900-5266-11ea-9aad-4e74499e367b.png)

**Comment by ganigeorgiev** [comment]
Merged in master and implemented in v2.9.0 release.

_Notes:_
- A project will be automatically unstarred/unpinned if you archive it
- Projects are first ordered by their starred/pin state and second by their creation date (DESC)

**Comment by ganigeorgiev** [comment]
Actually, this issue need a little more work.
The current implementation share the starred/pinned project state across all project owners which is not very clear from the interface and I guess most users will expect the star/pin action to be only for their listing. I'll try to update it the following days and will release it as v2.9.1

**Comment by ganigeorgiev** [comment]
Fixed in v2.9.1

**Comment by Laul0** [comment]
Tried just now !! It amazing and so useful 🤩🥳🙏

Thx so much for this new feature
