### ISSUE TITLE
"Collaboration"

### ISSUE THREAD

**Issue by ghs** [presentator/presentator#13]
"design collaboration and presentation platform" I know it was just released and the project is still in early stage, but right now the collaboration is a bit static.
Also know that the current technology used is not letting a real time collaboration, but will be really cool and provide with the collaboration people use to know and use.

Ex: Now when an user adds or removes a comment, hotspot or screen, others need to F5 or wait for email message (based on the case (and maybe personal settings)) in order to get to know about and see the change.

**Comment by ganigeorgiev** [comment]
Real live collaboration (or at least for notifications, comments and such) is planned for future releases, but I can't  tell exactly when (probably for **v1.0.1** or **v1.0.2**).

btw. It is also listed at the [project Patreon page](https://www.patreon.com/presentatorio) as one of it main goals.

**Comment by ghs** [comment]
Haven't arrived there yet :)

**Comment by ganigeorgiev** [comment]
Since the feature requires some major frontend changes and refactoring that could break the backwards compatibility with older versions, it will be rescheduled for v2.0 release.

**Comment by ganigeorgiev** [comment]
With v2 all new comments should be synced across users previewing a design.

With future 2.x releases additional sync states will be added (delete, reposition, etc.) but that will be handled in another issue(s).
