### ISSUE TITLE
Invalid or expired authorization token

### ISSUE THREAD

**Issue by katalysis** [presentator/presentator#131]
I've installed Presentator on my Centos server running Plesk. Everything looks fine, I'm seeing new users added to the database when created and I'm receiving notification emails etc.

However,  I cannot login to the accounts I'm creating, on activation and when trying to login I get the error: 

Oops, an error occurred while processing your request. on screen and in the logs/app.log:

2020-04-16 09:57:54 [81.150.177.91][-][-][error][yii\web\HttpException:401] yii\web\UnauthorizedHttpException: Invalid or expired authorization token. in /var/www/vhosts/presentator.katalysis.net/vendor/presentator/api/filters/HttpJwtAuth.php:77

**Comment by ganigeorgiev** [comment]
I've just created a registration on presentator.katalysis.net and the login request is successful (the user is with active status and a JWT token is generated), but it seems that the server is unable to verify the token when executing the other requests.

I'm not sure what the problem could be. I'd recommend to:
- check in you `params-local.php` config that all app keys/secrets (eg. `accessTokenSecret`) are not empty 
- run `php /var/www/vhosts/presentator.katalysis.net/vendor/presentator/api/requirements.php` to verify that there aren't any missing required extension
- enable debug mode and check the logs in https://presentator.katalysis.net/api/debug.

    To enable debug mode change `YII_DEBUG` to `true` and `YII_ENV` to `dev` in '/var/www/vhosts/presentator.katalysis.net/web/api/index.php' (or where the api public entrypoint is located);
     Also make sure that the debug module is enabled in your `api-local.php` config ([sample](https://github.com/presentator/presentator-api/blob/master/environments/dev/config/api-local.php)):
    ```php
    if (!YII_ENV_TEST) {
        // configuration adjustments for 'dev' environment
        $config['bootstrap'][] = 'debug';
        $config['modules']['debug'] = [
            'class' => 'yii\debug\Module',
            'allowedIPs' => ['*'],
        ];
    }
    ```

**Comment by ganigeorgiev** [comment]
Also make sure that Plesk is not filtering the `Authorization` header ([random blog post describing similar issue](https://www.ganey.co.uk/post/authorization-headers-in-plesk-linux))

**Comment by katalysis** [comment]
Thanks @ganigeorgiev  FcgidPassHeader AUTHORIZATION fixes the login issue.
