### ISSUE TITLE
Docker Setup Failing: Waiting for database connection..

### ISSUE THREAD

**Issue by pathikb** [presentator/presentator#134]
I am using docker to install the latest(2.5) version of presentator. I already have jwilder-nginx-proxy running. I setup mariadb docker instance like this -

```
docker run 
--name mariadb 
-p 3306:3306 
-e MYSQL_ROOT_PASSWORD=presentator -e MYSQL_USER=presentator -e MYSQL_PASSWORD=presentator 
-v /opt/data/mariadb/db:/var/lib/mysql 
-v /opt/data/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql 
-d mariadb:latest
```

And it works fine. After that, I tried running the presentator docker using the following command:

```
docker run       
--hostname abc.xyz.com       
--name presentator       
--link mariadb:mariadb       
--mount type=bind,source=/opt/data/presentator/php.ini,destination=/usr/local/etc/php/php.ini     
--mount type=bind,source=/opt/data/presentator/vhosts.conf,destination=/etc/apache2/sites-enabled/000-default.conf     
--mount type=bind,source=/opt/data/presentator/base-local.php,destination=/var/www/html/config/base-local.php     
--mount type=bind,source=/opt/data/presentator/params-local.php,destination=/var/www/html/config/params-local.php     
--mount type=bind,source=/opt/data/presentator/spa.json,destination=/var/www/html/config/spa.json     
--mount type=bind,source=/opt/data/presentator/storage,destination=/var/www/html/web/storage     
-e "LETSENCRYPT_HOST=abc.xyz.com" -e "LETSENCRYPT_EMAIL=abc@xyz.com" -e "VIRTUAL_HOST=abc.xyz.com"       
ganigeorgiev/presentator:2.5
```

However, when the docker runs, I see error in the console:
```
Warning: Invalid argument supplied for foreach() in /var/www/html/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php on line 122
Unknown component ID: db
Cannot connect to DB.
Waiting for database connection...
```

Any ideas what I am doing wrong?

**Comment by ganigeorgiev** [comment]
@pathikb It seems that the config file `base-local.php` is not properly formatted.

Here is a sample configuration file for comparison - https://raw.githubusercontent.com/presentator/presentator-docker/master/docker-compose-example/base-local.php

**Comment by pathikb** [comment]
Does the docker install create a default version of this file? I see that it has to be mounted on the host but do I have to create this file manually? When I run the docker instance, the file stays empty!

**Comment by ganigeorgiev** [comment]
Yes, when using the docker image all `*-local.php` that you want to override need to be created and mounted manually. For reference, you could also check the docker-compose example structure - https://github.com/presentator/presentator-docker/tree/master/docker-compose-example.

**Comment by pathikb** [comment]
Thanks I will try this and report back shortly!

**Comment by ganigeorgiev** [comment]
@pathikb You could also try running `composer install` (or `composer run-script post-install-cmd`) in the docker container so that it could run the initialization script and generate the env specific files that it needs.

**Comment by pathikb** [comment]
`composer install` gives the following error:

```
SQLSTATE[HY000] [1044] Access denied for user 'presentator'@'%' to database 'presentator'
Cannot connect to DB.
Script @php yii healthcheck/db handling the 1cb898515e7120a3a2631aad0c6a4fe11587569026 event returned with error code 1
```

**Comment by pathikb** [comment]
Alright, I realised mariadb docker container did not create the "presentator" database. I created manually and granted privileges to the user "presentator". Seems to have resolved the DB issue and console seems to tell me everything is doing ok but when I access the url through the hostname, it gives me

```
Forbidden
You don't have permission to access this resource.
```

Seems like a nginx-proxy issue!

**Comment by ganigeorgiev** [comment]
@pathikb Could you check if `docker.sock` is mounted in the `nginx-proxy` container (eg. `-v /var/run/docker.sock:/tmp/docker.sock:ro`)?

**Comment by ganigeorgiev** [comment]
@pathikb Also make sure that the app vhost is properly configured. Sample configuration - https://github.com/presentator/presentator/blob/master/packages/docker/docker-compose-example/vhosts.conf

**Comment by pathikb** [comment]
> @pathikb Could you check if `docker.sock` is mounted in the `nginx-proxy` container (eg. `-v /var/run/docker.sock:/tmp/docker.sock:ro`)?

Yes, no issue with this. Confirmed.



> @pathikb Also make sure that the app vhost is properly configured. Sample configuration - https://github.com/presentator/presentator/blob/master/packages/docker/docker-compose-example/vhosts.conf

The ServerName and ServerAlias was missing in the /etc/apache2/sites-available/default-ssl.conf which I have added and restart the container. However, the issue persists

The Presentator container tells me this in the logs:
```
AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
```

**Comment by pathikb** [comment]
Never mind, I updated the mounted vhosts.conf and not the apache hosts file inside the container. I FINALLY got it to work. Thank you so much for your help @ganigeorgiev Really appreciate it.
