### ISSUE TITLE
findProcessableQuery() should not be called statically

### ISSUE THREAD

**Issue by darkcarnage** [presentator/presentator#135]
Thanks for this great project and the quality of every detail!

I'm getting this error after scheduling the cron job :

`[error][yii\base\ErrorException:8192] yii\base\ErrorException: Non-static method presentator\api\models\UserScreenCommentRel::findProcessableQuery() should not be called statically in /home/user/public_html/mockups/vendor/presentator/api/commands/MailsController.php:36`

I just tried to declare the function `findProcessableQuery()` as static under `UserScreenCommentRel.php` :

![image](https://user-images.githubusercontent.com/872120/80843238-ae90d180-8bfb-11ea-9bde-a43f33b31c35.png)

And now it seems working :
`ea-php72 yii mails/process-comments`
`Processing unread screen comments...`
`Processed: 3`

Am I doing this right ?

Thanks.

**Comment by ganigeorgiev** [comment]
Yes, the method should be static.

A fix landed in v2.5.1 release. If you are using the starter package, just run `composer update` to get the latest changes.

_Side note: From the above error log I guess you are using shared hosting environment and it seems that you've placed the application files inside `public_html`, so make sure that only the project `web` directory is public accessible._
