### ISSUE TITLE
Add documentation for authentication methods

### ISSUE THREAD

**Issue by tridoan** [presentator/presentator#137]
Hey there,
Would be nice to have a section on how to setup to allow authentication with Google/FB/github/gitlab/etc. 

Im having some difficulty trying to figure out how to allow my install to allow users to login with these platforms. Maybe its easy, but i've not had to set something like this up before. Perhaps even just links to resources would be a good start. 

Thanks for this project, it looks great!

**Comment by ganigeorgiev** [comment]
@tridoan The default init setup should create a `base-local.php` with [commented OAuth configuration](https://github.com/presentator/presentator/blob/master/packages/api/environments/prod/config/base-local.php#L40-L79).

For example, if you want to allow authorization with Facebook:
1. [Register a Facebook app](https://developers.facebook.com/docs/apps#register) (the default permissions are fine, only the profile email is required).
    > Make sure for **Valid OAuth Redirect URIs** to set the same url as `authClientRedirectUri` from your `params-local.php` (by default it should be something like http://mydomain.com/#/auth-callback).

2. Add the following in your `base-local.php`:
```php
'authClientCollection' => [
    'class' => 'yii\authclient\Collection',
    'clients' => [
        'facebook' => [
            'class'        => 'yii\authclient\clients\Facebook',
            'clientId'     => 'YOUR_APP_CLIENT_ID',
            'clientSecret' => 'YOUR_APP_CLIENT_SECRET',
        ],
    ],
],
```

I'll update the readme/docs this weekend.

**Comment by ganigeorgiev** [comment]
The example setup was added under the [Installation section of the starter package](https://github.com/presentator/presentator/tree/master/packages/starter#allow-3rd-party-authentication-oauth2).
