### ISSUE TITLE
Time on uploads incorrect

### ISSUE THREAD

**Issue by tridoan** [presentator/presentator#139]
Hi there,
Im seeing an issue with the timestamp of uploaded images and comments, perhaps other things as well.
What i see after a timestampable action, is that the time will say something like "Uploaded 7 hours ago". It's always 7 hours behind.

I've checked my server's php setting, and the timezone is set to "America/Los_Angeles" as intended.  The same with the php.ini config. Mysql's settings are also set to Pacific time.  I looked in the database directly, and the timestamps are as expected.

I tested with a php file under /starter/web with the following code and it echoes the expected time:
```
<?php

$dt2=date("Y-m-d H:i:s");
echo $dt2;

?>
```
Do you know why the time shown in Presentator is off? 

Thanks.

**Comment by ganigeorgiev** [comment]
@tcitworld The application expects all dates to be in UTC (hence the 7 hour difference).

I'll consider explicitly defining the default php runtime timezone to UTC, bur to verify you could try updating your global server setting or add `date_default_timezone_set('UTC'); ` at the beginning of `/starter/web/api/index.php`

**Comment by tridoan** [comment]
Thanks you. Setting the server time to UTC worked.
