### ISSUE TITLE
Hotspots 2.0

### ISSUE THREAD

**Issue by ghs** [presentator/presentator#14]
Such as from Evernote or Awesome Screenshot. Based on the user profile (being designer, reviewer or whoever else), think different possibilities to annotate will bring better experience and easy ways to collaborate.

**Comment by ganigeorgiev** [comment]
I decided not to implement this feature because I think it could result in confusion between the preview, hotspots and comments modes. Screen comments could be used for leaving notes.

If anyone disagree, please comment and I'll reopen the issue.
