### ISSUE TITLE
Feedback: Show comment count in all modes

### ISSUE THREAD

**Issue by tridoan** [presentator/presentator#140]
Hi there,
I really appreciate the minimalism in design of this application. For the most part, it works and not only keeping the interface clean, but still very usable.

One improvement i would suggest though, would be to show to comment count of the current slide you're viewing, without having to click into the "Comments mode". This way, people will know there are comments available to interact with--especially for some non-technical users--so they will click into the Comment Mode. Otherwise, they wouldnt know to click into that mode to discover the comments or lack of comments.

This can be done simply, by just showing a number indicator on the Comment Mode call to action, like a notification barker.

Hope that made sense.

**Comment by ganigeorgiev** [comment]
Currently only a pulsating dot is visible in the preview when there are new unread comments: 
![New comments screenshoht](https://i.imgur.com/fPwGCjs.png)

I'll consider updating the bar layout for the next release (v2.6.0/v2.7.0).

**Comment by ganigeorgiev** [comment]
Comments counter for all primary unresolved screen comments is merged in master and available in v2.6.0 release.
