### ISSUE TITLE
Proposal: Annotation capabilities

### ISSUE THREAD

**Issue by tridoan** [presentator/presentator#142]
Similar to ticket 87, but not quite as extreme in feature-set. Where ticket 87 focuses more on the aspect of providing feedback based on the design comp currently in view, my proposal is more along the lines of the project owner providing supplemental descriptions (or annotations) to selected points on the design comp.

For example: Let's say you have a design comp of a home page for a new website. After you upload the design, you would put a annotation "pin" over the hero and write: Hero is a carousel slider composed of 4 slides fading in and out after 5 seconds.

As you can see, this allows you to provide additional context to the design at certain points that you see fit. 

This feature could technically be very similar to the Comments mode. The difference are that you wouldnt be able to reply and mark as resolve.  How i see this working is, Preview Mode, i would expect that there would be blinking markers over the comp indicating where a annotation pin was placed. Clicking on any of the annotation markers would open a panel to show all of the annotations on the current slide, with the clicked annotation highlighted. You can also click a call to action to toggle show/hide of the annotation panel independently.

Project owner or super admin, should be able to add/edit/delete annotations.

**Comment by Alecaddd** [comment]
I would very much interested in this feature.
I started using Presentator for Thunderbird design proposals and it's an amazing tool.
Great work!

**Comment by ganigeorgiev** [comment]
This is planned for v3 alongside other improvements - please check #183.

**Comment by ganigeorgiev** [comment]
Support for annotations as new hotspot type, both as "pin" and outlined area, is added in Presentator v3 (_you could expect to be publicly released in the next 1-2 weeks_).

The annotation pins/areas are visible by default in "Preview" mode but users can also hide them if they want to.
