### ISSUE TITLE
Switmailer not working

### ISSUE THREAD

**Issue by panchtatvam** [presentator/presentator#143]
### Stack

Using build [docker image](https://hub.docker.com/r/ganigeorgiev/presentator)

### Issue

When trying to register a new account with Swiftmailer configured, api/register can't process request. Is this an issue with swiftmailer or a docker issue ?

**Comment by ganigeorgiev** [comment]
@panchtatvam I wasn't able to reproduce the issue with the latest image tag.

Are you using SMTP (aka. `Swift_SmtpTransport`)? Could you paste your mailer configuration? Usually people forget to set `'useFileTransport' => false`.

You could also try using different mail server (for development and testing I'm using [mailtrap.io](https://mailtrap.io/)).

**Comment by panchtatvam** [comment]
Thank you. It seems there is something wrong with my email server.
The issue was fixed, being with my email server and not the app, when using mailtrap.io .
