### ISSUE TITLE
Proposal: analytics tools

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#144]
# Summary

It is an awesome web platform that allows people to connect and work on it. That could be awesome if we can add some Analytics tools configurations into the config file.

The most known tools seems to be:

* Google Analytics
* Matomo (formerly Piwik)

And rather than just add an Analytics tool, support Tag Manager of this two tools can be a powerful solution to let flexibility to the admins

Thank you for your job ❤️

**Comment by tridoan** [comment]
I think an easy way to achieve this is to allow a configuration to include your own js and css file. You can put whatever you want in those files to customize or include analytics code.

**Comment by ganigeorgiev** [comment]
@tridoan Enabling users to add their own js is prone to eventual xss vulnerabilities and will make handling CSP more difficult (see #30).

I'll keep the issue open, but personally, I don't see much benefit in marketing/analytics tools integration.

**Comment by Laul0** [comment]
Hi @ganigeorgiev 

For my use case, is not for marketing reason, is more to know the tool usage:

* The frequency
* The hit time per day
* When something is sharing to a client, to know how many external IP connect to a specific project
* Help to enforce the security. We know our clients, if one connexion is suspect, we can check the IP and add security
* Have a hit of project. Because designers share between them the projects and know which is the project the most consumed is really interesting
* Latency. If we need to implement a load balancer if the loading is too slow, etc

There are many cases for how an Analytics tool can be help the TI, the support and the final users.

**Comment by ganigeorgiev** [comment]
_Old issues cleanup in preparation for the upcoming Presentator v3._

There is no support for custom user defined JS because of the XSS concerns above but Presentator v3 is based on PocketBase so admins will have access to the activity logs UI which provides information about each API requests (like user IP, referrer, useragent, response time, etc.).
