### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by VT-nkumar** [presentator/presentator#149]
I'm getting blank screen after clicking on an image - /screens?mode=preview.  I'm using NGINX & starter package.  Is any step I missed while installation?

**Comment by ganigeorgiev** [comment]
@VT-nkumar 

Is this the full url you are trying to access? Make sure to check your nginx config for typos/misconfigurations (see [here](https://github.com/presentator/presentator/issues/120#issuecomment-539844456) for example)?

Are there any errors? To enable debug mode change `YII_DEBUG` to `true` in your `/web/api/index.php`.

**Comment by VT-nkumar** [comment]
![Screenshot from 2020-07-18 01-23-27](https://user-images.githubusercontent.com/63817798/87825811-6d709b00-c895-11ea-8f6e-d23a1daa0112.png)
@ganigeorgiev 

**Full URL** - https://domain.com/#/projects/1/prototypes/1/screens?mode=preview

NGINX configuration as per mentioned in the sample

I have enabled YII_DEBUG but no PHP side error or API side error.  Also in console, everything is blank.

**Comment by VT-nkumar** [comment]
@ganigeorgiev 

**api/hotspots?**page=1&per-page=200&envelope=true&search[prototypeId]=1 - Response is 
{status: 200,…}
headers: {vary: "Accept", x-pagination-total-count: 0, x-pagination-page-count: 0, x-pagination-current-page: 1,…}
response: []
status: 200

**/api/hotspot-templates?page=1&per-page=100&expand=screenIds&search[prototypeId]=1**
response - []

**/api/screen-comments?page=1&per-page=100&envelope=true&search[prototypeId]=1&search[replyTo]=0**
{status: 200,…}
headers: {vary: "Accept", x-pagination-total-count: 0, x-pagination-page-count: 0, x-pagination-current-page: 1,…}
response: []
status: 200

**Comment by ganigeorgiev** [comment]
Could you post the response of the prototypes endpoint (should be something like `/api/prototypes/1?expand=screens`)?

Also try temporarily to disable any chrome plugins that may interrupt the application js execution.

**Comment by ganigeorgiev** [comment]
In additional, to verify that this is not css related, please also post your current browser version (eg. `chrome://version/`).

**Comment by VT-nkumar** [comment]
> Could you post the response of the prototypes endpoint (should be something like `/api/prototypes/1?expand=screens`)?
> 
> Also try temporarily to disable any chrome plugins that may interrupt the application js execution.

This is the response /api/prototypes/1?expand=screens - **{"id":1,"projectId":1,"title":"Sample","type":"mobile","width":375,"height":812,"scaleFactor":1,"createdAt":"2020-07-17 18:47:18","updatedAt":"2020-07-17 19:29:21"}**

After disabling also I'm getting the same issue.

**Comment by VT-nkumar** [comment]
> In additional, to verify that this is not css related, please also post your current browser version (eg. `chrome://version/`).


Google Chrome | 84.0.4147.89 (Official Build) (64-bit)
-- | --
Revision | 19abfe7bcba9318a0b2a6bc6634a67fc834aa592-refs/branch-heads/4147@{#852}
OS | Linux
JavaScript | V8 8.4.371.19
Flash | 32.0.0.403 /home/serasdf/.config/google-chrome/PepperFlash/32.0.0.403/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --disable-gpu-rasterization --enable-features=HeavyAdIntervention --flag-switches-end
Executable Path | /opt/google/chrome/google-chrome

**Comment by VT-nkumar** [comment]
@ganigeorgiev - Even I tried in Firefox and the same issue.  The rest of the website is working fine but I cannot able to create a prototype because of this blank screen issue.

**Comment by ganigeorgiev** [comment]
@VT-nkumar The prototype response is missing the `screens` property, which means that probably the query parameter `expand` is not sent correctly to the api for some reason.

Could you verify that your are passing the query parameters to index.php in the /api location in your nginx config (aka. `$is_args$args;`)? Do you have cdn or other reverse proxy that could strip the query parameters?

To verify that this is related only to your setup, could you test the free service (https://app.presentator.io) and see if there any differences?

**Comment by VT-nkumar** [comment]
@ganigeorgiev - Thanks its working now.  It's problem with PHP FPM and NGINX configuration.  My NGINX configuration must be like **try_files $uri $uri/ /api/index.php?$query_string;**
