### ISSUE TITLE
Is it possible to prevent a new user to register?

### ISSUE THREAD

**Issue by Verhoeckx** [presentator/presentator#151]
Hello Presentator developers!

Is it possible to prevent a new user to register?
I installed Presentator on a shared web hosting environment and I am the only user.

**Comment by ganigeorgiev** [comment]
@Verhoeckx It is not possible to hide the "Sign up" form, but you can prevent other users to register by allowing only registration from your domain using the `onlyDomainsRegisterFilter` parameter in your `params-local.php`. For example:

```
'onlyDomainsRegisterFilter' => ['mydomain.com'],
```

**Comment by Verhoeckx** [comment]
Thanks! Perfect!

**Comment by Verhoeckx** [comment]
I added my domain name to the parameter _onlyDomainsRegisterFilter_ in the following file:
`./vendor/presentator/api/config/params.php`

**Comment by ganigeorgiev** [comment]
@Verhoeckx No, you have to modify your `params-local.php` (`-local.php` files are auto merged with their _original_ related files).

You shouldn't modify manually files located in the `vendor/` directory because they could be overwritten on `composer install/update`.

**Comment by Verhoeckx** [comment]
Oeps :flushed: !

I removed my domain in the file .`/vendor/presentator/api/config/params.php` and added it to the file `config/params-local.php`:sweat_smile:!
