### ISSUE TITLE
Email Template issues

### ISSUE THREAD

**Issue by tridoan** [presentator/presentator#152]
Hi there,
I've checked the html.php email template within /api/mail/layouts and noticed that there are my own defined values inserted, as expected, such as the Best Regards line and support email.

However, when an actual email gets triggered by my install, i still see the default values and messaging from the Presentator system (other than support email).

Is there any way to edit this email template file and have it reflected in the app, or is there something else that needs to be done to do this correctly?

Thanks.

**Comment by ganigeorgiev** [comment]
@tridoan There shouldn't be need to manually edit the mail template files (otherwise you risk your changes to be overwritten on update). All templates are parameterized by using `Yii->app->params`, or in other words - the default parameters could be changed by defining them in your `params-local.php`.

By default, when you first initialized the application the following defaults should've been added automatically:

```
    'baseStorageUrl'            => 'https://example.com/storage',
    'appUrl'                    => 'https://example.com/#/',
    'authClientRedirectUri'     => 'https://example.com/#/auth-callback',
    'activationUrl'             => 'https://example.com/#/activate/{token}',
    'passwordResetUrl'          => 'https://example.com/#/reset-password/{token}',
    'emailChangeUrl'            => 'https://example.com/#/change-email/{token}',
    'projectLinkUrl'            => 'https://example.com/#/{slug}',
    'projectLinkCommentViewUrl' => 'https://example.com/#/{slug}/prototypes/{prototypeId}/screens/{screenId}?mode=comments&commentId={commentId}',
    'commentViewUrl'            => 'https://example.com/#/projects/{projectId}/prototypes/{prototypeId}/screens/{screenId}?mode=comments&commentId={commentId}',
    'noreplyEmail'              => 'noreply@example.com',
    'supportEmail'              => 'support@example.com',
```
Full list with all parameters could be found at https://github.com/presentator/presentator/blob/master/packages/api/config/params.php

**Comment by tridoan** [comment]
Thanks, i got that. But i was trying to make some additional modifications to the email template, however, none of the changes a taking affect. Is there a possible cache issue, or something else?

**Comment by ganigeorgiev** [comment]
Hm, mail views aren't cached (at least not by default). All mail template files are located at `api/mail/`.

My guess is that maybe you are not editing the correct file(s). If you have used [presentator-starter](https://github.com/presentator/presentator-starter) for the installation, the files should be located at `vendor/presentator/api/mail`.

Could you provide more information about your setup?

**Comment by tridoan** [comment]
I think i figured it out. The file to modify is under this path, not the original i mentioned above
/html/starter/vendor/presentator/api/mail/layouts

Appears to work now as expected. Though, Im fully aware that an update will override everything. Just need something updated real quick
