### ISSUE TITLE
Question: Is it possible to show the Hotspots mode (H) in the Project links?

### ISSUE THREAD

**Issue by Verhoeckx** [presentator/presentator#153]
Hello Presentator developers,

Is it possible to show the Hotspots mode (H) in the Project links?
Is there a configuration for this?

Thanks,

Verhoeckx

**Comment by ganigeorgiev** [comment]
@Verhoeckx Do you mean to have an option to make the hotspot boxes always visible during previews?

**Comment by Verhoeckx** [comment]
Hello Gani,

As an administrator of a project I do see the Hotspots mode and this very convenient to see where all the hotspots are. But when I share my prototypes with my visitors they don't see that option. I think it's convenient for them to have this option too because in my prototypes it may not always be clear where the hotspots are. I do add a cursor icon to the locations that are clickable but they also may not always be immediately discoverable.

To be honest, my request is not very important because when a user clicks on an area that's not clickable the clickable areas are shown. Having said that: I think the hotspot icon at the bottom of the page can be very handy in exposing the feature more.

Hopefully I made myself clear :-).

Verhoeckx

**Comment by ganigeorgiev** [comment]
Added hotspots toggle control in [v2.8.0 release](https://presentator.io/news/2-8-0-release).

You could also preset the hotspots preview for your clients by sending them a preview url with the `hotspot=1` url query parameter.

**Comment by Verhoeckx** [comment]
Hello Gani,

That's great!! Thank you very much 😀 !!
I will update my installation in the next couple of day.

Regards Verhoeckx

**Comment by Verhoeckx** [comment]
I just upgraded to version 2.8 of Presentator (and I also updated Composer) and the 'Toggle hotspot' button works great!

🥳 🥳 🥳 😀
