### ISSUE TITLE
Documentation for backup & restore ??

### ISSUE THREAD

**Issue by christophdb** [presentator/presentator#158]
Hey there,
thanks for presentator. I am wondering what do I have to save to backup presentator. Is it enough to save:

- a database dump
- the config folder
- the uploaded files of the users

How do I do a restore? Normal installation and then just restoring the database and the files to the original position?
Thanks for any hint.
Best regards
Christoph

**Comment by ganigeorgiev** [comment]
@christophdb Yes, clean installation and after that restoring the database with the configs and the users files should be enough.
