### ISSUE TITLE
Comments box looses comment text if clicking out of box before clicking 'send'

### ISSUE THREAD

**Issue by TonyBarganski** [presentator/presentator#162]
We loose our 'long' comments occasionally if we accidentally click outside of the comment box before clicking on the send/post icon. 

In my humble opinion, it might serve better to not do anything with the comment data and leave the comment textarea open when clicking outside of it. 

Additionally, most web entry tools I use these days tend to make pressing “Enter” a commit function (instead of “Ctrl+Enter”) to save a comment.  Newlines are made with “Shift+Enter” but this is just convention.

**Comment by ganigeorgiev** [comment]
Unsent comments are now kept until page refresh (v2.8.2).

The shortcut for submitting a comment is kept unchanged to avoid confusion and accidental comment submission. In addition,  InVision also uses `Ctrl + Enter` so I guess people coming from there are already accustomed with it.
