### ISSUE TITLE
Proposal: OAuth2 Does Not Read/Display Users Profile Picture

### ISSUE THREAD

**Issue by TonyBarganski** [presentator/presentator#164]
On other systems where we use our Self-Hosted GitLab server as an authentication provider, we see the GitLab profile picture automatically for our user account once logged in. Would be great if this could be automated.

**Comment by ganigeorgiev** [comment]
_Old issues cleanup._

This is fixed in Presentator v3, which if nothing unexpected show up, should be publicly available within the next 1-2 weeks.
