### ISSUE TITLE
Proposal: "Toggle Fit to Screen" - make this the default setting

### ISSUE THREAD

**Issue by TonyBarganski** [presentator/presentator#166]
We typically open 10-15 design slides per day at the moment and most of the design slides we view, we have to click the "toggle fit-to-screen" button. It would save a lot of time if this could be the default or at least a global setting somewhere that we can switch on.

<img width="234" alt="Toggle fit to screen" src="https://user-images.githubusercontent.com/46673133/104149249-9312d300-53e6-11eb-8ee4-2f2cf7d5293e.png">

**Comment by ganigeorgiev** [comment]
With v2.13.0 the "Fit to screen" selection is stored in the local storage so now your last selection should be preserved (the `fit` query parameter remains with higher priority).
