### ISSUE TITLE
Proposal: View comments I have made

### ISSUE THREAD

**Issue by TonyBarganski** [presentator/presentator#167]
Currently, I do not see "my" "comments count" displayed on the prototype view list. I also don't see my comments in the Notifications area. I do however, see them if logged in as another user.

A use case we have a lot is to go back to a slide/prototype we’ve added comments to and add more comments there to elements that are common across a number of slides/prototypes. This way, our designer is not constantly flipping from screen to screen and can better get a picture on one or two slides of what we are after.

Can we enable "comment counts" and "Notifications" for our own user?

Currently, we log in twice as a work-around with another user account.

<img width="371" alt="User comments" src="https://user-images.githubusercontent.com/46673133/104205827-e8c79980-543f-11eb-922a-e317ea643a70.png">

**Comment by ganigeorgiev** [comment]
@TonyBarganski The count your are seeing is actually the unread screen comments.

I'd consider adding a general "Comments" view/section within a project in future releases.

**Comment by ganigeorgiev** [comment]
@TonyBarganski In v2.9.0 I've updated the screen comments counter to be always visible and to take in consideration all primary comments (aka. pins).

_Note that the counter will be still highlighted when there are unread comments. A more generic "Comments" view/section will be implemented in future releases._
