### ISSUE TITLE
Bug: Adding 2nd reply to a comment & deleting 1st reply deletes all replies completely

### ISSUE THREAD

**Issue by TonyBarganski** [presentator/presentator#168]
Unexpected behaviour as I haven't clicked to delete all replies, only the 1st reply.

<img width="678" alt="Screen Shot 2021-01-12 at 12 52 08" src="https://user-images.githubusercontent.com/46673133/104298457-0e52b280-54d5-11eb-9ec3-42ca952c30c2.png">

**Comment by ganigeorgiev** [comment]
This is intentional (although the UI may need a little improvement?). The first comment is a "primary comment" (aka. the pin itself) and all following comments actually represent a reply to the primary one.

**Comment by ganigeorgiev** [comment]
I just noticed a typo in the confirmation message - "to deleted...". Fix was released in v2.8.3.
