### ISSUE TITLE
Invalid or expired authorization code (OAuth to GitLab provider)

### ISSUE THREAD

**Issue by TonyBarganski** [presentator/presentator#169]
The first time I logged in this worked. Subsequently, trying to login with a different OAuth GitLab account fails with message:

"**Invalid or expired authorization code.**"

We've tried to delete GitLab & Presentations Cookies/Local Storage on the browser but same error message.

Original account which logged-in using OAuth 'can' still authenticate and Sign-in. 

Tried setting up an Application on gitlab.com as a test and added the clientId & clientSecret to the Presentator base-local.php config file but still received the same error message.

**Comment by ganigeorgiev** [comment]
@TonyBarganski Could you check if the gitlab account's email is allowed in your register email domain filter?

**Comment by TonyBarganski** [comment]
> @TonyBarganski Could you check if the gitlab account's email is allowed in your register email domains filter?

@ganigeorgiev This fixed the problem, thank you!
Pity the error message was not a little more telling. I presume its a generic message from the OAuth provider.
