### ISSUE TITLE
Presentation view

### ISSUE THREAD

**Issue by mvwijland** [presentator/presentator#172]
Possibility to present the screens to a group of people. Where you have a cursor that can point to items on a screen. 

You can share a link to a group of people. 
When the open the link, the presenter controls the navigation of all persons in the group.
Other have a cursor with their name attached in various colors that only allows them to point out something to the others. But they have no control over the screen. 

This is the basics, a first iteration to make presenting to a remote group possible.

**Comment by ganigeorgiev** [comment]
That's interesting request, It seems similar to #87 but with additional real live interactivity.

Unfortunately at the current stage of the project this will be very complex to implement and will require major changes (probably even a different techstack more compatible with WebSockets/EventStreams).

I'll close the issue for now, but it is definitely something I'll consider for v3.
