### ISSUE TITLE
Attempting to run in production mode, cannot register thus cannot use. 400 (Bad Request)

### ISSUE THREAD

**Issue by smartlot** [presentator/presentator#173]
Using the docker-compose file after removing Nginx as I already run a public Nginx proxy. Created a public domain and am forwarding from my public proxy to the internal host. Accessing via local IP or domain returns the same error, after a short pause, and prevents me from registering a user. Have attempted numerous hosts as well config modifications. 

I can usually deploy docker stacks fairly efficiently, but I'm lost here, not enough of an error message to even begin. If anyone can point me in the right direction, I'd truly appreciate it.

**Console:**
```
chunk-vendors.6a80195f.js:19 POST http://192.168.100.1/api/users/register 400 (Bad Request)
(anonymous) @ chunk-vendors.6a80195f.js:19
e.exports @ chunk-vendors.6a80195f.js:19
e.exports @ chunk-vendors.6a80195f.js:26
Promise.then (async)
o.request @ chunk-vendors.6a80195f.js:26
(anonymous) @ chunk-vendors.6a80195f.js:19
value @ chunk-vendors.6a80195f.js:26
onSubmit @ chunk-e8827032.192f359c.js:1
submit @ chunk-e8827032.192f359c.js:1
nt @ chunk-vendors.6a80195f.js:72
n @ chunk-vendors.6a80195f.js:72
Xa.i._wrapper @ chunk-vendors.6a80195f.js:72
```

**Method throwing exception:**

```
 "0c92": function(e, t, n) {
        /*! 2020 Presentator API JS Client https://presentator.io */
        !function(t, n) {
            _e.exports = n()_
```

**Presentor stack (Docker logs):** 

192.168.100.100 - - [11/Feb/2021:22:59:55 +0000] "POST /api/users/register HTTP/1.1" 400 661 "http://192.168.100.1/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

**Web page toast error message:** 
"Oops, an error occurred while processing your request"

**No error from the MariaDB stack.**

**Comment by ganigeorgiev** [comment]
@smartlot Just to make sure that we are on the same page, you are using the [production docker image](https://github.com/presentator/presentator/tree/master/packages/docker), right?

It is hard to tell what is causing the error. It could be due to unmounted or wrong configurations (check base-local.php, params-local.php).

Could you inspect also the 400 error response in the browser's Inspect tool (f12 > Network)?

**Comment by ganigeorgiev** [comment]
@smartlot I forgot to mention that you could also ssh in your presentator container and enable the application debug mode for more detailed error messages - edit `/var/www/html/web/api/index.php` and change `YII_DEBUG` constant to `true`.

**Comment by smartlot** [comment]
The network tab includes three entries, chunk-e8827032.192f359c.js, auth-clients, register.

The only error comes from register:

`{message: "Oops, an error occurred while processing your request.", errors: {}}
`

**Comment by smartlot** [comment]
I've enabled DEBUG but I do not detect any extra output via console log or docker logs.

Same error, no detail to lead me further...

`{message: "Oops, an error occurred while processing your request.", errors: {}}
`

**Comment by smartlot** [comment]
The Network console for the host shows this message, but Javascript is certainly enabled on the browser.

`We're sorry but Presentator doesn't work properly without JavaScript enabled. Please enable it to continue.`

**Comment by ganigeorgiev** [comment]
@smartlot Hm, could you try to inspect the logs in your `/var/www/html/runtime` directory?

Could you also verify that the db migrations are applied successfully - is there a `User` table?

_The JavaScript note is expected because you are previewing the raw html._

**Comment by smartlot** [comment]
DB Migrations look to be fine:

```
DB connection is established.
> @php yii migrate/up --interactive=0
Yii Migration Tool (based on Yii v2.0.40)
No new migrations found. Your system is up-to-date.

```

Now, after looking at the app.log file, this error is repeated over and over again, which seems to be at the root of the issue:

```
2021-02-12 15:49:31 [10.4.0.4][-][-][warning][yii\caching\FileCache::setValue] Unable to write cache file '/var/www/html/config/../runtime/cache/26/26a95287bcfa6477294b76f98051743a.bin': file_put_contents(/var/www/html/config/../runtime/cache/26/26a95287bcfa6477294b76f98051743a.bin): failed to open stream: No such file or directory
2021-02-12 15:49:31 [10.4.0.4][-][-][info][application] $_GET = []

```

Not sure what file or directory it's looking for or what I have to replace/correct in order to fix this issue.

**Comment by ganigeorgiev** [comment]
I'm not sure why you get that warning, but I doubt that it is responsible for the register error. My guess is that the user create transactions fails for some reasons but there should be an `[error]` log if that was the case. Could you try submitting the form and check the log again?

_Another possible "debug" approach is to manually add `var_dump($e->getMessage());exit;` in `/var/www/html/vendor/presentator/api/models/forms/UserCreateForm.php` before [line 172](https://github.com/presentator/presentator/blob/master/packages/api/models/forms/UserCreateForm.php#L172)_

**Comment by smartlot** [comment]
Okay, I added the line before line 172, now the registration "goes through", or at least I get the 'Check your email to finish signing up. We sent a signup link to you at' though no email is even attempted, as seen from the Mailgun logs. Also, no new error messages to speak of other than this under register in the network console tab:
`string(52) "Expected response code 220 but got an empty response`

**Comment by smartlot** [comment]
This is the console output after "registering" a user.

```
192.168.100.100 - - [12/Feb/2021:16:44:28 +0000] "GET /spa-resources/fonts/ubuntu-v13-latin_cyrillic-300.4bb889b3.woff2 HTTP/1.1" 200 51324 "http://10.4.0.115/spa-resources/css/app.986855d4.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


192.168.100.100 - - [12/Feb/2021:16:44:28 +0000] "GET /spa-resources/fonts/ubuntu-v13-latin_cyrillic-700.96e550fb.woff2 HTTP/1.1" 200 40800 "http://10.4.0.115/spa-resources/css/app.986855d4.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


192.168.100.100 - - [12/Feb/2021:16:44:28 +0000] "GET /spa-resources/fonts/feather-icons.ea390915.ttf HTTP/1.1" 200 83239 "http://10.4.0.115/spa-resources/css/app.986855d4.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


192.168.100.100 - - [12/Feb/2021:16:44:28 +0000] "GET /spa-resources/fonts/ubuntu-v13-latin_cyrillic-regular.8d685859.woff2 HTTP/1.1" 200 47444 "http://10.4.0.115/spa-resources/css/app.986855d4.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


192.168.100.100 - - [12/Feb/2021:16:44:28 +0000] "GET /api/users/auth-clients HTTP/1.1" 200 609 "http://10.4.0.115/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


192.168.100.100 - - [12/Feb/2021:16:44:29 +0000] "GET /spa-resources/js/chunk-0a8cc030.9fac4dbf.js HTTP/1.1" 200 1551 "http://10.4.0.115/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


127.0.0.1 - - [12/Feb/2021:16:44:35 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.14 (internal dummy connection)"


127.0.0.1 - - [12/Feb/2021:16:44:36 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.4.14 (internal dummy connection)"


192.168.100.100 - - [12/Feb/2021:16:44:37 +0000] "GET /api/users/auth-clients HTTP/1.1" 200 610 "http://10.4.0.115/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


192.168.100.100 - - [12/Feb/2021:16:44:39 +0000] "POST /api/users/login HTTP/1.1" 400 633 "http://10.4.0.115/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


192.168.100.100 - - [12/Feb/2021:16:44:41 +0000] "GET /api/users/auth-clients HTTP/1.1" 200 610 "http://10.4.0.115/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


192.168.100.100 - - [12/Feb/2021:16:44:53 +0000] "POST /api/users/register HTTP/1.1" 200 638 "http://10.4.0.115/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"


      
```

**Comment by ganigeorgiev** [comment]
@smartlot it seems that that your mailer is not properly configured. Please check if the correct port/encryption is provided.

**Comment by smartlot** [comment]
Well, all I did was change the port on Mailgun settings from 465 to 587 and now I received the welcome email. Odd. Thank you for all of the assistance in getting this running, looking into diving into the project. Kudos!

**Comment by smartlot** [comment]
Now I am having an issue with reverse proxying requests from an Nginx server on another host. I'm trying to decipher exactly what I am missing as this Nginx proxy currently handles dozens of applications w/o issue.

**Comment by smartlot** [comment]
Figured it out, modified the local Nginx in another issue to adapt for reverse proxying! Yes, I am finally in and can get to work. Again, thanks for all of the assistance. Cheers!

**Comment by ganigeorgiev** [comment]
I'm glad that you were able to make it work.
I'm closing the issue, but If you stumble on something, please comment or open a new one.
