### ISSUE TITLE
Proposal: Hide navigation in preview mode following hotspot behavior

### ISSUE THREAD

**Issue by dmartinjs** [presentator/presentator#174]
Firstly, thanks for this great application !

I would like to hide the navigation element in preview mode.

2 options possible:
- add a parameter to hide them
- hiding them by default and follow the same behavior as hotspot

<img width="381" alt="navigation-between-screens" src="https://user-images.githubusercontent.com/53537199/110241636-16b5ef80-7f52-11eb-9cac-90185912ba3e.png">

**Comment by ganigeorgiev** [comment]
This is similar to #154.

Since this is probably the third request for this feature, I'll take it in consideration for the next release (v2.10)

**Comment by ganigeorgiev** [comment]
Implemented in v2.10.0 release.

The screen navigation will not be displayed, if the following conditions are met:
1. Is in Preview mode
2. The current active screen has at least one hotspot
3. The preview bar is hidden
