### ISSUE TITLE
Proposal: overview of screens with hotspot paths

### ISSUE THREAD

**Issue by dmartinjs** [presentator/presentator#175]
I would like to have an overview of all the screens with the hotspot paths to find and see all the interactions added to screens as in other prototyping tools.

### Adobe XD
![adobe-xd](https://user-images.githubusercontent.com/53537199/110243266-ec683000-7f59-11eb-8d40-1402acdf171e.png)

### Overflow

<img width="689" alt="overflow" src="https://user-images.githubusercontent.com/53537199/110242668-664aea00-7f57-11eb-9c0a-98c9acd5b449.png">

### Figma

<img width="693" alt="figma" src="https://user-images.githubusercontent.com/53537199/110243274-f4c06b00-7f59-11eb-83cf-191777340a2a.png">

### Sketch

<img width="1269" alt="sketch" src="https://user-images.githubusercontent.com/53537199/110243322-16b9ed80-7f5a-11eb-9c96-e2a76004db7d.png">

**Comment by ganigeorgiev** [comment]
_Old issue cleanup._

This for now remains out of the scope for Presentator v3.
