### ISSUE TITLE
Proposal: Device skins

### ISSUE THREAD

**Issue by dmartinjs** [presentator/presentator#176]
In preview mode, I would like to visualise screens in a real device mockup when display in a large screen (desktop, tv).

### overflow
https://support.overflow.io/hc/en-us/articles/360005922673-Device-Skins-and-Masks

![_Add device skin to beautify_TIP#8](https://user-images.githubusercontent.com/53537199/110243560-36054a80-7f5b-11eb-89cb-ee4dc10825d2.gif)

### Figma

https://help.figma.com/hc/en-us/articles/360039823894-Set-prototype-device-and-starting-frame

![Options menu (6)](https://user-images.githubusercontent.com/53537199/110243750-01de5980-7f5c-11eb-8e3e-8b660497fdfc.png)

**Comment by ganigeorgiev** [comment]
_Old issue cleanup._

For now this feature requests remains out of the scope of Presentator v3, which will be released in the next 1-2 weeks.

If there is enough users demand I may reconsider it but I think it will be hard to maintain and I don't have the time to spent on this at the moment.
