### ISSUE TITLE
Presentator v3 Roadmap discussion

### ISSUE THREAD

**Issue by ganigeorgiev** [presentator/presentator#183]
Hi everyone,

I'd like to share with the community my plans for the next major version of Presentator and where the project is headed in general.

**Without further ado, here is a short list of some of the currently planned changes and features for Presentator v3:**
1. Rewrite in Go and distribute as a single executable file (embedding the frontend, api and database) for easier self-hosted installation (**breaking - no more shared-hosting support!**)
2. Redesign the frontend for more modern and cleaner UI
3. Actual real-time collaboration support without relying on external services
4. Better invite/share flow
5. Prototype screens sections/grouping (eg. #146)
6. Draw and annotate over the shared designs (eg. #87, #142)
7. Finer controls over the received user notifications (eg. #83)
9. Better incorporate the "Guidelines" feature in to the project prototypes
9. Improve thumbs generation and memory consumption
10. Super admin dashboard with some basic api metrics (eg. #144)
11. (*) Allow users to have a public portfolio page to showcase their designs (like in Behance or Dribbble but without the pesky ads and tracking;  _depending on my schedule, this feature may not be included in the first v3 release_)

The most breaking and time consuming change will be rewriting and redesigning the platform using Go.

**Why the switch from PHP to Go?**

Presentator has grown quite a lot since its first release in ~2016/2017. Not only the public free service ([app.presentator.io](https://app.presentator.io)) has already 12000+ registered users with more than 140GB+ uploaded files but there are also a lot of people self-hosting the platform. Which has led to numerous issues and support requests related to difficulties installing and properly configuring Presentator. In addition, the PHP API limits our options for real-time collaboration and you either have to further complicate the setup using something like Swoole or rely on 3rd party services like Pusher or Firebase.

This is why at the end of 2021 I decided to start working on a new general purpose backend written in Go - for now I've named it **PocketBase**.  **It will be a separate project but all its features will be aligned with what we'll need for Presentator.**
It is inspired by [Nhost](https://nhost.io) and [Supabase](https://supabase.com/) but rather relying on several different microservices, PocketBase will have everything included in itself - authentication, SQLite database with real-time subscriptions, files handling and super admin dashboard. The end result would be a Go library that will allow us to build quickly single executable platforms by just doing something like:
```go
package main

import pb "pocketbase"

func main() {
  pb.New().
    AddListener("BeforeUserApiCreate", func (e *pb.Event) {
      // some Presentator specific logic...
    }).
    Start()
}
```

If you are curious, this is how PocketBase dashboard currently looks like:
![PocketBase screenshot](https://i.imgur.com/NErtc7r.png)
_(it is still a very early MVP but you could also explore some of the other screenshots here - [https://app.presentator.io/#/6mote1hf](https://app.presentator.io/#/6mote1hf))_

---

**Release schedule:**
- [x] finalize the unit tests and documentation for PocketBase and release it by the end of Q2/Q3 this year (the project repo(s) will be located here https://github.com/pocketbase)
- [x] somewhere around Q4 (or Q1/Q2 the next year) release Presentator v3, including:
  - migration script to automate the upgrade from v2 to v3
  - new AdobeXD and Figma plugins to work with the new v3 api
  - new landing site and api documentation

**Please share your thoughts and what else you would like to see in Presentator v3 :)**

**Comment by ganigeorgiev** [comment]
**One big step towards Presentator v3 has been completed** - [PocketBase](https://pocketbase.io), the new to be backend for Presentator v3, has been just published :tada:.

You could check https://github.com/pocketbase/pocketbase and share some feedback.

**Comment by ganigeorgiev** [comment]
@iskrisis Thanks for the suggestion. As far as I know, there are usually 3 approaches for this:

v1. Create a "screenshot" of the website on server-side and upload it to Presentator like a regular image
- require complicated and resource heavy server setup
- may not always work, especially on websites with loading animations and a lot of js to execute

v2. Load the external url in an iframe and leave comment on a layer on top of it.
- this is the easiest way
- unfortunately, sometimes this is considered a vulnerability and most websites have CSP/iframe policies and allows iframes (if at all) only for the same domain
- because of the responsive of the website, comments may not be positioned correctly on all resolutions

v3. Create a browser extension and "inject" the comments in the html
- **this is the best and most reliable way** to implement this, because it allows us to interact with the actual html page, so we can make it work even on responsive
- Requires both ends to have the browser extension installed in order to be used

I haven't used https://www.markup.io but I'll investigate it in the future to see how they do it.

**Comment by hungcrush** [comment]
Hi @ganigeorgiev I just want to tell you, I really love what do you do. I love your UI design.

Presentator v3 with Pocketbase.. It will be awesome.. Hope to see it soon..

**Comment by ljfreelancer88** [comment]
I would love to contribute with this roadmap and also enhance my knowledge in Go.

**Comment by ganigeorgiev** [comment]
Sorry for the lack of news for anyone still following here.

**If nothing unexpected show up, Presentator v3 is going to be released next Sunday, 28.01 (_or the week following it in the worst case scenario_).**

I'm currently finalizing some automated tests and polishing touches, and will gradually update the repos within the next couple days.

Presentator v3 is fully rewritten from scatch (both the API and the UI) and comes with multiple improvements:

- single executable for easier self-hosting (based on PocketBase)
- extendable via Go or JS, allowing listening to various app events like new comments for sending notifications to Slack or other external source
- realtime comments notification without the need of Firestore
- better notifications control
- better and improved OAuth2 support
- hotspot annotations
- 3x-6x speed up on average for the most "heavy" list requests
- new simplified and refreshed UI
- and many more

There are also some deprecated and removed functionality in v3:

- No i18n support.
  Over the last couple years, this has proven to be difficult to maintain and keep up with new development, so I've decided to remove the translations support in v3.
  If there is enough users demand and I may reconsider it, but I don't think it will be necessary as the UI is greatly simplified.
  Additionally, almost all modern browsers have some builtin auto translations support (including recently [Firefox Automated translation](https://support.mozilla.org/en-US/kb/website-translation)).

- No Adobe XD plugin.
  The future of Adobe XD is unclear and Adobe hasn't yet made an official statement after the failed Figma acquisition whether they will continue the development of XD or plan to shut it down
  (even the official XD download links seems to be no longer available or at least not listed in the Creative Cloud offerings).
  With that said, a new version of the [Figma plugin](https://www.figma.com/community/plugin/791989050714284849/presentator-export) is already deployed and it should work with both Presentator v2 and v3 APIs.
  If the situation around XD changes, I'll reconsider updating the existing XD plugin in a similar manner.

- Removing the projects "Guideline" support.
  After discussions with some designers and based on the hosted service data, to simplify the UX I've decided to remove the support of the project "Guideline" section.
  This feature was rarely used because it was very limited and most users seem to preferred exporting their project specs as full Artboard(s) (mostly because it provided more flexibility and control on what and how the overall design specs are visualized).

_Note1: For those who self-host Presentator note that there will be a dedicated migration command line tool to semi-automate the migration process (the migration tool is "incremental" and can be run safely several times to accommodate moving large datasets on portions)._

_Note2: The discussed above URL design feedback for now remains out of the initial scope for v3 as I don't have time at the moment to work on it but may reconsider it in the future._

**Comment by compgeniuses** [comment]
could you consider a penpot integration

**Comment by ganigeorgiev** [comment]
@compgeniuses I haven't tried Penpot but I don't think it has a plugin API (or at least I can't find information about it).

**Comment by compgeniuses** [comment]
i think you are right, the issue is detailed here: https://github.com/penpot/penpot/discussions/462

As for API documentation, they do have one, but it uses rPC, and is available here: https://design.penpot.app/api/_doc

For most, i think we might want to wait for v2 release: https://tree.taiga.io/project/penpot/epic/2662

**Comment by ganigeorgiev** [comment]
Presentator v3 is finally public.

Most of the repos were updated (only the Docker Hub image remains but that will be done a little bit later today).

The free hosted service (https://app.presentator.io) was also migrated and everything should be working properly.

If you stumble on something, please report it in the repo issues tracker or on the _support [at] presentator.io_ mail.

**Comment by elioqoshi** [comment]
I wanted to say that I am saddened by the removal of the guidelines feature. It proved to be very useful for us to provide a link for clients without sending them zips. Is there any chance that feature could be reintroduced?

**Comment by ganigeorgiev** [comment]
@elioqoshi No sorry, at least for now I'm not planning reintroducing them.
