### ISSUE TITLE
Cannot Upload image size more than 1 mb

### ISSUE THREAD

**Issue by Winniepoom** [presentator/presentator#186]
Hello I'm using presentator docker version everything seem to be fine for me except one thing that bug me which is I can't upload image more than 1mb no matter what type of image I try to increase memory limit but it seem don't work for me 
![zxfca](https://user-images.githubusercontent.com/107398226/174716786-782ed6af-1671-42a0-add3-177f45e15f15.png)
 
post_max_size       = 512M
upload_max_filesize = 512M
max_execution_time  = 60
memory_limit        = 2048M

I'm try to enable YII debug mode but it seem don't work  for me

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'prod');

require __DIR__ . '/../../vendor/autoload.php';
require __DIR__ . '/../../vendor/yiisoft/yii2/Yii.php';

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/../../vendor/presentator/api/config/base.php'),
    require(__DIR__ . '/../../config/base-local.php'),
    require(__DIR__ . '/../../vendor/presentator/api/config/api.php'),
    require(__DIR__ . '/../../config/api-local.php')
);

**Comment by ganigeorgiev** [comment]
By default the max screen upload size should be 10MB. To change this and other file size limits, you'll have to add in your `params-local.php`:
```
// maximum allowed screen file upload size in MB
'maxScreenUploadSize' => 10,

// maximum allowed user avatar file upload size in MB
'maxAvatarUploadSize' => 3,

// maximum allowed guideline asset file upload size in MB
'maxGuidelineAssetUploadSize' => 15,
```
All available parameters could be found here - https://github.com/presentator/presentator-api/blob/master/config/params.php

To see more detailed error/debug logs, you'll also have to change `YII_ENV` to `dev`.

**Comment by ganigeorgiev** [comment]
Hm, I'm not sure what is causing the above error.

Could you please post your error logs?

**Comment by Winniepoom** [comment]
there are nothing in app.error.log it just empty 
![xga](https://user-images.githubusercontent.com/107398226/174771795-4bddb0b7-da0d-4c64-a75a-8462ba3bb1a5.PNG)

**Comment by Winniepoom** [comment]
here are a log. look like error came from nginx docker I check mariadb and presentator I didn't see any error when upload image
![zxcagggg](https://user-images.githubusercontent.com/107398226/174786343-f81fb602-e7e7-4830-9748-3a21687b638c.PNG)

**Comment by ganigeorgiev** [comment]
Ah, I understand now. It seems that the [default body size of the nginx reverse proxy  is 1mb](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size).
To change it:
1. Create a custom configuration file, eg. `my_proxy.conf`:
```
client_max_body_size 100m;
```
2. Mount your custom config as volume to the `nginx-proxy` container in your `docker-compose.yaml`, eg. it should look something like this:
```
nginx-proxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - 80:80
  volumes:
    - /path/to/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
```

_For other alternatives ways of changing the default configurations you could check the README section of the nginx-proxy image - https://hub.docker.com/r/jwilder/nginx-proxy._

**Comment by Winniepoom** [comment]
Thank you that solve my error now 
you are the best [ganigeorgiev](https://github.com/ganigeorgiev)
