### ISSUE TITLE
Proposal: Plugin export including linked elements

### ISSUE THREAD

**Issue by viko-wtf** [presentator/presentator#190]
It would be great if the Presentator plugin for Adobe XD would be able to export the links from prototypes as well. 

Use Case: In our company, we UX designers are faster at creating prototypes (i.e. linked artboards) directly in XD in our workflow. 
It would be helpful if these links (or the respective elements) could be transferred directly into hot zones and links. Currently, we would have to create our protoIt would be great if the Presentator plugin for Adobe XD would be able to export the links from prototypes as well. 

Use Case: In our company, we UX designers are faster at creating prototypes (i.e. linked artboards) directly in XD in our workflow. 
It would be helpful if these links (or the respective elements) could be transferred directly into hot zones and links. Currently, we would have to create our prototypes in XD to test them internally and then create them again in Presentator's web interface to share with the team. Unfortunately, this is duplicate work and makes the otherwise good tool less attractive. The native prototype feature of XD is just easier for us. In presentator, however, linking is still important in retrospect, for example, if other ideas arise during a workshop.  types in XD to test them internally and then create them again in Presentator's web interface to share with the team. Unfortunately, this is duplicate work and makes the otherwise good tool less attractive. The native prototype feature of XD is just easier for us. In presentator, however, linking is still important in retrospect, for example, if other ideas arise during a workshop.

**Comment by ganigeorgiev** [comment]
Thanks for the suggestion. I'll have it mind when reworking the Adobe XD plugin for v3.

Unfortunately this may not easy to implement since it depends on your workflow, especially if some users prefer to do partial exports. Also it kinda depends on what type of prototype relations are created within Adobe XD - whether there any animations/transitions used, popover screens, etc.

In your case, it may be easier to just use the builtin Adobe XD share tool - https://www.adobe.com/products/xd/learn/collaborate/stakeholder-review/presenting-sharing-with-clients.html

**Comment by viko-wtf** [comment]
Thanks for the quick response :) 

I understand the implication and possible complications of our request. 
... we would already be happy with the base functions of the prototypes. So without any animations or other effects. 

Your suggestion of Abobe's own tool for sharing is of course obvious. Unfortunately, our privacy policies are a bit stricter, so it's out of the question for us to use the Adobe Cloud, to which all this is tied. 
So we are currently looking for an on primise solution like Presentator offers us (almost!)  

Thanks anyway. 
We will keep an eye on your development.  :)

**Comment by ganigeorgiev** [comment]
With the unclear future of XD and my lack of time to, this feature requests for now remains out of the scope for Presentator v3.
