### ISSUE TITLE
Is this still being actively developed?

### ISSUE THREAD

**Issue by tridoan** [presentator/presentator#194]
Just curious since i do not see any recent activity.

**Comment by ganigeorgiev** [comment]
Yes and sorry for the lack of news.

I've recently updated my open source projects priority and decided to focus more on Presentator (see https://github.com/pocketbase/pocketbase/discussions/3271)

In short, I'm actively working towards Presentator v3. I'm having some difficulties with the UI but the good news is that the backend part is already complete (_*remains only automated tests and the v2->v3 migration scripts_). My current plan is to release it by the end of this year.
