### ISSUE TITLE
Support for Russian (ru-RU) language

### ISSUE THREAD

**Issue by kerimovok** [presentator/presentator#195]
I added all the missing translations that were in [transifex](https://app.transifex.com/presentatorio/web-platflorm/language/ru_RU/), can you view and check them? I couldn't test locally (maybe because I'm on Windows), so if you can please do so.

(I don’t know how to do PR, that’s why I’m creating an issue)
Russian is my second native language and I live in the CIS, if you have any questions or nuances, you can clarify

I tried to compare everything with the UI so that everything would match in meaning (example: Archive is a verb, not a noun in the menu -> [Архив](https://translate.google.com/?sl=ru&tl=en&text=%D0%B0%D1%80%D1%85%D0%B8%D0%B2&op=translate) - [Архивировать](https://translate.google.com/?sl=ru&tl=en&text=%D0%B0%D1%80%D1%85%D0%B8%D0%B2%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C&op=translate))

Most likely there will still be some inaccuracies, but you can run it in BETA mode and I can view everything in working form.

Also made shorting in some places (Адрес электронной почты -> [Email](https://ru.wikipedia.org/wiki/%D0%AD%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BF%D0%BE%D1%87%D1%82%D0%B0#:~:text=%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%20%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C%20%D1%81%D0%BE%D0%BA%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BE%D1%82%20%C2%AB%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F%20%D0%BF%D0%BE%D1%87%D1%82%D0%B0%C2%BB%20%D0%BA%D0%B0%D0%BA%20%C2%ABemail%C2%BB%2C%20%D0%B0%20%D0%BD%D0%B5%20%C2%ABe%2Dmail%C2%BB) / Эл. почта)

**Comment by ganigeorgiev** [comment]
Thank you but with the upcoming Presentator v3 the translations will no longer be valid (sorry for this, I forgot to mention it in the transifex page announcements).

I'm also planning to deprecate the i18n support as it is too difficult to maintain and we had some troubles with malicious users in the past adding offensive or wrong translations on purpose (_I try to roughly verify the strings with Google Translate but it takes a lot of time_).
