### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by mvwijland** [presentator/presentator#196]
Hi Gani, Thank you for providing us with this new version of the presentator. I would like to run it internally, but we are running on Apple MACs (Intel and M2). How do I create a local working version? Can you add some text in the READMe about building the application?

**Comment by ganigeorgiev** [comment]
Please follow the instructions from https://github.com/presentator/presentator?tab=readme-ov-file#local-setup.

It should be enough to download the binary for your platform, in your case I guess that would be the `darmin_arm64` version - https://github.com/presentator/presentator/releases/download/v3.1.0/presentator_3.1.0_darwin_arm64.zip.

**Comment by ganigeorgiev** [comment]
If you want to build the binary from the repo on your own:

1. [Install Go 1.21+](https://go.dev/doc/install)

2. Clone/download the repo.

3. Navigate to `/base` directory.

4. Run `CGO_ENABLED=0 go build . -o ./presentator`

5. Execute the created binary with `./presentator serve`.

If you need further help, feel free to elaborate what exactly did you find difficult and I'll update the instructions.

**Comment by ganigeorgiev** [comment]
To avoid eventual confusion since it is not clear what do you mean by the plural in "we are running on Apple MAC**s**" note that Presentator is a web application and it needs to be installed on a web server (aka. it is not a desktop application and users can access it from their web browser)._

**Comment by mvwijland** [comment]
Gani, great, thank you. I will run this on one of our Mac servers.

**Comment by ganigeorgiev** [comment]
But again, note that you don't need to build anything. Presentator v3 is based on top of PocketBase and it contains everything (including the database) in the prebuilt binary.

There are no dependencies or anything extra that needs to be installed. Just make sure to download the correct binary for your platform and follow the [Local setup](https://github.com/presentator/presentator?tab=readme-ov-file#local-setup) instructions.

If you are not able to run the binary from your Mac you can check the instructions how to enable its execution from this related issue https://github.com/pocketbase/pocketbase/issues/2819.
