### ISSUE TITLE
[Question] How to create new collection ?

### ISSUE THREAD

**Issue by santoshgistto** [presentator/presentator#198]
Thanks for this project, 
I would like to know how we can  create new collection in admin dashboard  ?

**Comment by ganigeorgiev** [comment]
It is not clear what do you mean.

Even if you create a new collection, where and what you'll do with it?

In any case, Presentator is based on PocketBase so you can refer to its documentation if you want to extend it - https://pocketbase.io/docs.

By default in Presentator the collections modify controls are hidden but can be enabled from the PocketBase Admin UI > Settings > Application > "Hide collection create and edit controls" toggle.

If you need further help, please don't treat the issues tracker as llm chat and try to elaborate more on your use case to understand the bigger picture and what you are trying to do.
