### ISSUE TITLE
Reg solution approach

### ISSUE THREAD

**Issue by insidesmart** [presentator/presentator#199]
Presentator is a nice product. Thanks & Kudos for making it open source and supporting it all along.

I was looking for some example nodejs web application projects made with pocketbase as a base and found presentator in my search.

If I understand correctly, presentator leverages pocketbase for lot of features but still it should be considered as a go based application (as some of the features are implemented in go) and not pocketbase extended with go.

Any reasons why it is done that way ? My core question is - why all go related features cannot be implemented via pb_hooks (using js). Wouldn't that be way easier to maintain (whenever pocketbase is updated) ? Were you missing some ready compatible npm packages to build on top of it ?

Just want to understand the reasons behind the choices made. That might help in deciding the solution approach in my projects.

**Comment by ganigeorgiev** [comment]
It is not clear what you are asking and I don't have the energy in pointless discussions, especially in the issues tracker.

PocketBase **IS** a Go framework. The JSVM (pb_hooks/pb_migrations) is an optional [plugin](https://github.com/pocketbase/pocketbase/tree/master/plugins/jsvm) and all exported apis are autogenerated from the Go code.

For extending PocketBase please read https://pocketbase.io/docs/use-as-framework/.

For why PocketBase was created, you could read https://github.com/presentator/presentator/issues/183.

**Comment by insidesmart** [comment]
Thanks for taking time to provide the links.
