### ISSUE TITLE
Disable Register Option

### ISSUE THREAD

**Issue by zebulondev** [presentator/presentator#201]
Hello,

How to disable register option on frontend? The way is on Extend with JS OR need to rebuild ?

![Capture d’écran, le 2024-11-14 à 13 03 23](https://github.com/user-attachments/assets/83e497a9-29b6-49bd-a732-137034d129da)

**Comment by ganigeorgiev** [comment]
There is no option to hide the register link but you can disable the user create API endpoint:

1. Temporary uncheck the "Hide collections create and edit controls" in the _PocketBase Admin UI > Settings > Application_.
2. Navigate to _Collections > Users > Edit collection cogwheel > API rules > Create API rule > Set Admin only_ and save the collection.

When a regular user authenticate to register it should fail with an error.
