### ISSUE TITLE
Login without E-Mail verification

### ISSUE THREAD

**Issue by mms-gianni** [presentator/presentator#202]
I am running Presentator on a Kubernetes cluster but lack access to SMTP, preventing me from validating my email and completing registration. 

It would be helpful to have an initial admin account or the option to disable email verification for easier onboarding. Since it runs on Kubernetes, I prefer using environment variables.

**Comment by ganigeorgiev** [comment]
Admins (superusers with PocketBase v0.23.0-rc) can manage the Presentator users from the PocketBase dashboard, aka. `http://127.0.0.1:8090/_/`.

Option to disable verification is already available, again through the PocketBase dashboard. Go to:
1. Temporary enable the Collections create/edit controls from _PocketBase Admin UI > Settings > Application > "Hide collection create and edit controls"_ toggle (http://127.0.0.1:8090/_/#/settings).

2. Navigate to _PocketBase Admin UI > Collections > users > "Edit collection" cogwheel > Options_ and uncheck the "Forbid authentication for unverified users" checkbox.

3. Enable back the "Hide collection create and edit controls" toggle from 1) to prevent accidental schema changes.
