### ISSUE TITLE
Any documentation or references to customise the UI

### ISSUE THREAD

**Issue by sunnydadigs** [presentator/presentator#203]
Thank you for the excellent app, Presentator! I am new to Go and Pocketbase, and I followed the instructions to successfully deploy the app to production.

The next step is to customize the user interface by changing some colors and updating the logo, among other things.

However, the installation only includes the `pd_data` folder and nothing else. I would like to know how to customize the templates and user interface.

I read in the Pocketbase documentation that the installation should include the `pb_public` folder. Therefore, I downloaded the presentation repository and placed it in the `pb_public` folder, but it doesn't seem to be working.

Could you please guide me to any tutorials or reference documentation that would help me customize the frontend? Thank you!

**Comment by ganigeorgiev** [comment]
It is not clear what you are trying to do but the user interface cannot be customized at the moment (or at least not without forking).

There are no plans for now to allow customization for the UI.

**Comment by sunnydadigs** [comment]
Hello,
I mean updating the logo to our own logo and change the colour codes to match our brand colour codes etc as we are self-hosting.
![image](https://github.com/user-attachments/assets/c66cfdb7-52ab-4b8b-b17f-f12a9636c4d1)

**Comment by ganigeorgiev** [comment]
I see. Unfortunately it is still not possible at the moment (there is a note at the end of the [Configurations](https://github.com/presentator/presentator?tab=readme-ov-file#configurations) section about it).

It will be added sometime in the future but I have too many things on my hand right now and for the time being remains a low priority.
