### ISSUE TITLE
Designs analytics and usability testing

### ISSUE THREAD

**Issue by ganigeorgiev** [presentator/presentator#30]
As @m.antonova suggested, It would be nice to:
- Have some statistic info how users interact with the presented designs (clicks, cursor heatmap, time, etc.).
- Implement functionality to create user tasks and usability tests.

**Comment by filtercake** [comment]
would be an idea to be able to hook in standard piwik or google analytics code?

**Comment by ganigeorgiev** [comment]
Because of eventual issues with the Content-Security-Policy header and XSS vulnerabilities, I decided to not implement this feature.

Better option would be implementing new "User test" mode for the project previews, but that will be handled in another issue.
