### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by Wiredframe** [presentator/presentator#36]
Presentator is a great tool and deserves much more attention. I suggest you to setup a Twitter account and do a little marketing.

**Comment by jdittrich** [comment]
It might be a good idea, but I suggest to define first what the gains & pains would be. What does @ganigeorgiev want? :-)

It might be a way to gain more donations, that would be good; it means also more work.

**Comment by ganigeorgiev** [comment]
It will be nice to setup a Twitter account (for posting info about new releases, current status of the [presentator.io](https://presentator.io) services, etc.), but currently I hardly have time to handle with the email support and the project [Facebook](https://www.facebook.com/presentator.io) and [Google+](https://plus.google.com/u/0/communities/114548328830374165880) pages, so creating a Twitter account will be postponed for now until I find a better way to manage my free time.

**Comment by Wiredframe** [comment]
Honestly, Facebook is not the right place for promoting such a tool. Twitter is perfect for this. For example: InVision is tweeting something about it's tool a neutral account can recommend @presentator and link to its account. Perfect marketing that reaches the right people who already knew about InVision but didn't know about Presentator.

**Comment by marcus-herrmann** [comment]
Regarding this topic, I wrote an article for the small German print magazine SCREENGUIDE (www.screengui.de) about presentator. It will be released with the next issue in December. Although this magazine is rather niche, maybe more people are interested about this project and will look for a way to subscribe. This could either be a Newsletter or a twitter account (both not so unusual forms of marketing among web developers). Both, the list and the account could in a first step collect subscribers, so @ganigeorgiev has an audience when he finds the time to "broadcast"/publish

**Comment by ganigeorgiev** [comment]
Just to let you know, I've recently created a Twitter account for Presentator - https://twitter.com/presentatorio. Mainly release notes and current status of the free service (https://presentator.io) will be posted  there. Please note that I'm not very active social media user (I rely on email notifications) and I could be slow to response.
