### ISSUE TITLE
Suggestion: Replace Screen while keeping the comments

### ISSUE THREAD

**Issue by Wiredframe** [presentator/presentator#38]
It would be nice to replace a screen while keeping the comments.

**Comment by ganigeorgiev** [comment]
Implemented as a new screen setting tab and included in v1.5.0 release:
![Replace screen image demo](https://i.cubeupload.com/ID1XfX.png)

**Comment by Wiredframe** [comment]
Awesome! Thank you very much for adding this feature!

**Comment by der-On** [comment]
@ganigeorgiev This feature is gone in v2.x :(

**Comment by ganigeorgiev** [comment]
@der-On I'll try to implement it in the next release.

**Comment by der-On** [comment]
:kissing:

**Comment by ganigeorgiev** [comment]
Merged in master and released in v2.3.0: ![Replace screen demo](https://i.imgur.com/Z0YcEKj.png)
