### ISSUE TITLE
Styleguide for a project

### ISSUE THREAD

**Issue by ghost** [presentator/presentator#41]
It could be awesome to have a styleguide 
integrated into a project with colors, typography, main images.
![styleguide](https://user-images.githubusercontent.com/13915512/32024185-288ec916-b9cb-11e7-9262-b387728178ac.png)

**Comment by ganigeorgiev** [comment]
@ucodi Do you know any other platforms that have implemented it or have an idea how it should looks in the end? Also is it expected the style guide to be uploaded by the user manually or to be auto generated by the platform (note that only the most frequently used colors could be extracted from the image files)?

**Comment by ucodi** [comment]
## Board in Invision (https://www.invisionapp.com/)
![invision-board](https://user-images.githubusercontent.com/13915512/32241638-9ecfeb7c-be68-11e7-9ffd-6705a544f9f0.jpg)

## Styleguide in Zeplin (https://zeplin.io/)
example here : https://scene.zeplin.io/project/55e80ad1b0a7da160ff25004

I think people should have control of it, so it should be added manually like add colors one by one (perhaps provide a colorpicker fo screens and import swatches, add font manually and assets too.

I tried something but I was not really inspired and it's ugly...

**Comment by ganigeorgiev** [comment]
@ucodi Thanks for the examples. I'll try to implement it in **v1.5.0**/**v1.6.0** milestone.

**Comment by Xaviju** [comment]
It might be nice to join forces with the people of identihub, an Open Source Styleguide platform: https://demo.identihub.co/login
If interested, you should ping @uracreative or @elioqoshi

**Comment by elioqoshi** [comment]
@ganigeorgiev Would be definitely great to have you on Identihub :)
It's still Alpha but has a good amount of features for now. Also, we are really open to features requests and PR's so you can shape the roadmap as well. You should be able to register for a demo without our help, but let me know if there is anything!

Would love to collaborate!

**Comment by ganigeorgiev** [comment]
@elioqoshi thanks, I'll check it later :)

**Comment by elioqoshi** [comment]
@ganigeorgiev sure, if you need help with the style guide I can help out as well :)

**Comment by lazmo88** [comment]
+1 definitely valuable add-on for Presentator

**Comment by ganigeorgiev** [comment]
New "Guideline" mode was introduced with v2 (master).
The current implementation is very robust and allows only files upload (jpg, png, svg, zip, pdf, fonts, psd, etc.) and project colors definition.

Please open a new issue if you have a suggestion for improvement.
