### ISSUE TITLE
Hotspot modes: Close and Back

### ISSUE THREAD

**Issue by der-On** [presentator/presentator#56]
As a user I want to be able to create a hotspot that brings me back to the previously opened screen (required if #54 is implemented) and I want to be able to create hotspot closing the currently overlayed screen (#55)

**Comment by der-On** [comment]
This is covered in the prototype for #55 https://app.presentator.io/de/roO8LmFy?v=0&s=6&m=preview

**Comment by ganigeorgiev** [comment]
Implemented in v2 (master).
