### ISSUE TITLE
Use React/Preact/Vue.js + Redux for the UI

### ISSUE THREAD

**Issue by der-On** [presentator/presentator#58]
As presentator comes with a REST-API it could serve as a starting point for implementing at least parts of the UI with modern technologies like React/Preact/Vue.js + Redux instead of jQuery. This could improve the speed of feature development, as this stack allows for rapid development of complex UIs.

**Comment by ganigeorgiev** [comment]
Thanks for the suggestion. Actually I've already thought of rewriting the frontend with vue/react for v2.0 but need to take some time to consider over the pros and cons of using a full featured frontend framework (except the project screen related stuffs like adding comments, hotspots, etc. there is not many js code).

For me, the problem with new features development is not the frontend or backend part of it, it is the design one. It is very easy to bloat the platform with a lot of features (almost every week I receive a new suggestion), but creating usable and simple to use interface takes a lot of time (and in addition to that I'm not very good designer).

**Comment by der-On** [comment]
Thank you for your feedback on this. Vue.js is indead also an option. I just realized that creating UIs with a VDOM-like technology together with a single source of thruth state/store UI code get's a lot more robust and predictable.

Regarding the design part, I for now can provide you with mockups or even prototypes (created in presentator of course). In the furture I have two designers who can help out. We want to migrate from Invision to a self hosted FOSS we can customize/extend to our needs.

**Comment by ucodi** [comment]
I'm preparing API calls right now, and I'll start design interface and build view with React this week.

**Comment by ucodi** [comment]
I'm learning React and I'm starting to develop a front with it, so I open issues for API features and when the code will be stable enough I will open a PR.

**Comment by mariojankovic** [comment]
If you ever consider using Vue.js, I could rewrite the app I guess. Would love to see it maintained in the future, it's an amazing tool! I am also super proficient with HTML/CSS, so I think I could take that weight off your shoulders.

**Comment by ganigeorgiev** [comment]
I've already started rewriting the platform using Vue.js + Vuex. As stated on the readme page - expect the new version to be release mid May/June 2019.

**Comment by spazola** [comment]
Will you use the same design or a new one ?

**Comment by ganigeorgiev** [comment]
@spazola No, a new design (and new logo) is already in progress.

**Comment by der-On** [comment]
@ganigeorgiev Huge thanks for all your work! This is amazing news. Can we see the new design somewhere? Maybe even in the presentator app itself?

**Comment by ganigeorgiev** [comment]
@der-On You could check a draft version for some of the screens here - https://app.presentator.io/RzSmv8xC, but nothing is fixed so keep in mind that the final version could differ from the mockups.

**Comment by Cruiser13** [comment]
Looking forward to the 2.0 Vue.js release!

**Comment by ganigeorgiev** [comment]
Presentator v2 is merged in master. There is still a lot of things that could to be improved, but I think it is stable enough to be released. 

All presentator repos are moved under the [presentator](https://github.com/presentator) organization account.
The Vue.js app repo is located at [presentator/presentator-spa](https://github.com/presentator/presentator-spa).
For those who host the platform on their own server - check [presentator/presentator-starter](https://github.com/presentator/presentator-starter).
