### ISSUE TITLE
Proposal : Favorite

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#75]
# Current behavior

When you have a lot of projects, all of them are listed and the older are at the bottom of the page (you have to click on "Load more Project" to see them)

# Expected behavior

Add a star on tile that allow to identify the project as favorite one and put it at the top or create a specific view that allow to see all favorites projects.

**Comment by ganigeorgiev** [comment]
@Laul0 I'm closing this in favor of #128 because it is very similar and may clutter the UI unnecessary.

If anyone disagree, please comment and I'll consider reopening the issue.

**Comment by Laul0** [comment]
You're right. I have totally forgotten this issue
