### ISSUE TITLE
Proposal : Archive

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#76]
# Current behavior

All projects even old them are listed on the projects board.

# Expected behavior

Add a "feature" that allow to identify a project as "Archived" (a tag) and hide it from the default projects view.
To see the archived project, add a dropdown list that allow to see the archived project

## Example of overview

| Closed Menu | Opened Menu |
|--------------|---------------|
| ![presentator-scope-projects-closed](https://user-images.githubusercontent.com/15279205/43585066-752c388c-9664-11e8-8bbc-5003d060fef5.png) | ![presentator-scope-projects-opened](https://user-images.githubusercontent.com/15279205/43585088-7c6dee60-9664-11e8-868c-fc3f3282a4b8.png) |

**Comment by Laul0** [comment]
To add a project into archives, add a link in to the ellipsis that already exist :
![presentator-archiveellispsis-project](https://user-images.githubusercontent.com/15279205/43585930-9b453350-9666-11e8-9896-dcceed85edb2.png)

**Comment by Laul0** [comment]
The archive feature can allow to prevent users to edit screen (comment, hotspot, settings) too

**Comment by ganigeorgiev** [comment]
Implemented in v2 (master).

p.s. Note that with the current implementation archived projects are still public accessible.
