### ISSUE TITLE
Proposal : Search on screen

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#78]
# Current behavior

We're allow to perform a search from the projects view. It is really useful when they're a lot of projects.

# Expected behavior

Like the projects view, add a search bar that allow to perform a search on the screens view. That will be really useful when an user want to retrieve a specific screen mostly when there are a lot of screens.

## Overview

![presentator-screenssearch](https://user-images.githubusercontent.com/15279205/43586473-01badd78-9668-11e8-8eae-a208176eaf00.png)

**Comment by ganigeorgiev** [comment]
Implemented in v2 (master).
