### ISSUE TITLE
Proposal : Notification per project

### ISSUE THREAD

**Issue by Laul0** [presentator/presentator#83]
# Summary

To allow the users to keep in touch when a comment is deposited, this one receive one or several e-mail.

# Current behavior

By default, the user receive an e-mail for each comment added to projects screens, for every projects.
It is possible to disable notifications (for all)

# Expected behavior

Let the possibilities to disable notifications for specific project, because it's possible to work on severals projects and for some of them it's not necessary to received any notification.

**Comment by ganigeorgiev** [comment]
Just to let you know, with the v2 release there is a notification panel that you could filter unread comments by project. Emails are sent every half an hour (or depending on your cron setup) for only those comments that are not marked as "read".

Email notification settings per project will be implemented in future v2.x releases.

**Comment by ganigeorgiev** [comment]
_This is fixed in Presentator v3, which if nothing unexpected show up, should be publicly available within the next 1-2 weeks._

Users now have option to watch/unwatch individual projects.
