### ISSUE TITLE
Proposal : Canvas Mode

### ISSUE THREAD

**Issue by jkornobis** [presentator/presentator#87]
## Add a shared layer based on a canvas library to annotate a screen directly

1. Add a button in edit and/or comment-view mode.

2. Implement a library with a toolbar for drawing 

3. Share the layer to all members (nice to have : dedicated color per member) to do like the screen : move icon or remove it with a virtual marker (red here).

![canvas-mode](https://user-images.githubusercontent.com/1469418/46336003-bc4e3180-c629-11e8-9466-71e93ec9afbf.jpg)

**Comment by der-On** [comment]
:+1:

**Comment by ganigeorgiev** [comment]
This is planned for v3 alongside other improvements - please check #183.

**Comment by ganigeorgiev** [comment]
_Old issue cleanup._

This was rejected in favor of the new more simple hotspots annotations that will be available with the upcoming Presentator v3 in the next 1-2 weeks.
