### ISSUE TITLE
Proposal: Additional file types

### ISSUE THREAD

**Issue by lazmo88** [presentator/presentator#91]
It would be great to share pdf, psd, html and other files directly to Presentator. At the moment only jpg and png seems to be supported.

**Comment by ganigeorgiev** [comment]
At least for now, I don't think there is an easy way to visualize pdf or psd files and use them for a project screen (currently they are used mainly as under layer for drawing hotspots and comments).

But uploading fonts and other design resources will be definitely included in https://github.com/ganigeorgiev/presentator/issues/41

**Comment by ganigeorgiev** [comment]
Support for svg and other image formats was added in v2 (master).
