### ISSUE TITLE
Inspect feature

### ISSUE THREAD

**Issue by ghost** [presentator/presentator#95]
With SVG support, it will be possible to implement an Inspect feature for developers similar to [Inker](https://zaaack.github.io/inker/)

### Target feature

feature similar to [Avocode](https://avocode.com/hand-off-and-inspect) or [Zeplin](https://zeplin.io)

<img width="800" alt="capture d ecran 2019-02-07 a 00 40 05" src="https://user-images.githubusercontent.com/40141083/52381285-2f9cff80-2a71-11e9-9c18-124e136d4d8d.png">

<img width="800" alt="capture d ecran 2019-02-07 a 00 39 32" src="https://user-images.githubusercontent.com/40141083/52381300-3b88c180-2a71-11e9-8244-115d5b3d42ad.png">

**Comment by ganigeorgiev** [comment]
Although svg support was added in v2, the inspect feature requires very different approach (Presentator is more focused on the "presentation part" of the design workflow) and I decided not to implement it (at least for now).
